### ISSUE TITLE
Error in fetching user rank in leaderboard !

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#891] opened 2024-10-18 20:35 UTC
Details : https://www.loom.com/share/881adfab24264b04a2d0fdc8590e2f57?sid=ca7e3e70-aa71-4e6e-818d-74feb5346b4b

**Comment by ooochoche** [comment] 2024-10-19 05:26
@revengexd GM. If no one is working on this, I can start.

**Comment by snehaa-eth** [comment] 2024-10-20 14:11
GM, can i take up this issue,?

**Comment by od-hunter** [comment] 2024-10-21 14:21
Can I work on this asap please? @revengexd

**Comment by josephchimebuka** [comment] 2024-10-22 03:45
Can I handle this? I will review the code and check for error logs to see the specific error I will also review the ranking query to see if i will see any errors. Then I will fix it

**Comment by ikemHood** [comment] 2024-10-24 07:05
This might be due to this callback (particularly the tenary operation), 
```ts
  const fetchPageData = useCallback(async () => {
    const requestBody = {
      addr:
        status === "connected"
          ? hexToDecimal(address && address?.length > 0 ? address : userAddress)
          : "",
      page_size: 10,
      shift: 0,
      duration: timeFrameMap(duration),
    };

    setRankingdataloading(true);
    await fetchLeaderboardToppersResult({
      addr: requestBody.addr,
      duration: timeFrameMap(duration),
    });
    setRankingdataloading(false);
  }, [
    fetchRankingResults,
    fetchLeaderboardToppersResult,
    address,
    userAddress,
    status,
  ]);
```
not sure but would have look deep into it and prolly test|debug it when i am assigned

**Comment by ikemHood** [comment] 2024-10-24 07:11
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
This might be due to this callback (particularly the tenary operation), 
```ts
  const fetchPageData = useCallback(async () => {
    const requestBody = {
      addr:
        status === "connected"
          ? hexToDecimal(address && address?.length > 0 ? address : userAddress)
          : "",
      page_size: 10,
      shift: 0,
      duration: timeFrameMap(duration),
    };

    setRankingdataloading(true);
    await fetchLeaderboardToppersResult({
      addr: requestBody.addr,
      duration: timeFrameMap(duration),
    });
    setRankingdataloading(false);
  }, [
    fetchRankingResults,
    fetchLeaderboardToppersResult,
    address,
    userAddress,
    status,
  ]);
```
not sure but would have look deep into it and prolly test|debug it when i am assigned

**Comment by Benjtalkshow** [comment] 2024-10-24 08:25
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will start by investigating the API calls used to fetch the user rank in the leaderboard. I'll make sure the right data is being retrieved for each time period, like "all time" and "last 30 days." If I find an issue with caching or old data being reused, I will fix the state management so that it properly updates when the user switches between time frames.

I will also check the rank calculation on the backend to make sure it's accurate for all time periods and properly handles the user's data. Once everything is working, I will test it to ensure the leaderboard displays the correct rank for the user in all cases.

**Comment by bruhhgnik** [comment] 2024-10-24 08:45
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Gm, i have recently worked on other blockchain projects and starting to gain experience in the field

### How I plan on tackling this issue
I'll analyse the API calls used to fetch the user rank in the leaderboard.
I think i need a day or lesser to fix this.

**Comment by fricoben** [comment] 2024-10-24 09:09
assigned @Snehagupta1907

**Comment by GradleD** [comment] 2024-10-26 06:59
` import { useCallback, useEffect, useState } from 'react';
import { useAccount } from 'yourAccountProvider'; // Update the import to match your setup
import { hexToDecimal, timeFrameMap } from 'yourUtilityFunctions'; // Ensure correct imports

const LeaderboardComponent = () => {
   const { status, address } = useAccount();
   const [ranking, setRanking] = useState([]);
   const [leaderboardToppers, setLeaderboardToppers] = useState([]);
   const [rankingdataloading, setRankingdataloading] = useState(false);
   const [apiCallDelay, setApiCallDelay] = useState(true);

   const fetchPageData = useCallback(async () => {
      const userAddress = status === "connected" ? address : "";
      const requestBody = {
         addr: hexToDecimal(userAddress ?? ""),
         page_size: 10,
         shift: 0,
         duration: timeFrameMap(duration),
      };

      console.log("Starting fetchPageData with requestBody:", requestBody);
      setRankingdataloading(true);

      try {
         const topperData = await fetchLeaderboardToppersResult({
            addr: requestBody.addr,
            duration: requestBody.duration,
         });
         console.log("Leaderboard toppers fetched:", topperData);

         const rankingData = await fetchRankingResults(requestBody);
         console.log("Ranking data fetched:", rankingData);

         if (topperData && rankingData) {
            setLeaderboardToppers(topperData);
            setRanking(rankingData);
         } else {
            console.warn("No data found for leaderboard or ranking.");
         }
      } catch (error) {
         console.error("Error fetching leaderboard data:", error);
      } finally {
         setRankingdataloading(false);
      }
   }, [fetchRankingResults, fetchLeaderboardToppersResult, address, status]);

   useEffect(() => {
      if (apiCallDelay) {
         fetchPageData();
         const delayTimer = setTimeout(() => setApiCallDelay(false), 5000); // Adjust delay if needed
         return () => clearTimeout(delayTimer);
      }
   }, [fetchPageData, apiCallDelay]);

   return (
      <div>
         {/* Render leaderboard data */}
         {rankingdataloading ? (
            <p>Loading...</p>
         ) : (
            <div>
               {/* Display rankings and leaderboardToppers as needed */}
            </div>
         )}
      </div>
   );
};

export default LeaderboardComponent; `


**Logging**: Console logs are added to track:

**The requestBody for API requests.**
Data returned from fetchLeaderboardToppersResult and fetchRankingResults.
Error Handling: A try-catch block around API calls ensures that any network or response issues are caught, with an error logged for easier troubleshooting.

**Conditional Checks**: Added a check to ensure both topperData and rankingData contain data before updating the state.

**Timeout Handling**: The setTimeout in useEffect now clears itself to prevent memory leaks.

**Comment by Marchand-Nicolas** [comment] 2024-10-29 13:11
Hello @Snehagupta1907 Is everything ok ?

**Comment by Marchand-Nicolas** [comment] 2024-10-30 09:56
Hey @Snehagupta1907, I will assign someone else if I don't have any sign of life

**Comment by snehaa-eth** [comment] 2024-10-30 10:12
Hello yes sorry @Marchand-Nicolas i was sick so took some days  off..

**Comment by snehaa-eth** [comment] 2024-10-31 20:17
Is this issue fixed? @Marchand-Nicolas 

https://github.com/user-attachments/assets/87f9bfdd-19e7-486c-9f70-26024c1a567d

**Comment by Marchand-Nicolas** [comment] 2024-11-01 13:49
@Snehagupta1907 
No, the bug is still present, but it happens a bit randomly. Also, sometimes, it shows the wrong data for a few seconds, and then it gets automatically replaced by the right data.
![image](https://github.com/user-attachments/assets/c0ed9d77-6b76-44cc-9164-e89460980875)
(Here it should clearly not show people with 60xp but more something like 500xp.)
To reproduce the bug, you can watch the video made by @revengexd again and try reproducing the same steps

**Closed as completed** 2024-11-02 21:04 UTC
Labels: 🚨 Important bug, open for contribution
