### ISSUE TITLE
Navbar elements to fix

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#975] opened 2024-12-03 14:39 UTC
## Description 📹

**There is a slight shift of the navbar elements when clicking on the notification icon. Can we fix the elements?**
https://www.loom.com/share/77b2578a874042fabb38bbfc4ce6d6d7

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by OWK50GA** [comment] 2024-12-03 14:41
Hi, I can solve this

**Comment by SudiptaPaul-31** [comment] 2024-12-03 16:07
@Marchand-Nicolas @Kevils Can I work on this?

**Comment by michojekunle** [comment] 2024-12-05 07:20
Hello, May I handle this issue?

To fix the navbar element shift when clicking the notification icon. 

Here’s my plan:

- Analyze Behavior: Identify the root cause of the navbar shift when the notification icon is clicked.
- Implement Changes: Adjust styles or layout to ensure the navbar elements remain static during interaction.
- Test Locally: Verify the fix works across different screen sizes and doesn’t break functionality.
- Submit PR: Follow the repo’s workflow, referencing the issue in the PR.

### ETA: 24 Hours

Looking forward to your approval to proceed!

**Comment by Pvsaint** [comment] 2024-12-05 13:36
Can I take this issues? I'm a frontend and smart contract developer and a first time contributor in this repo.
If assigned this issue, ETA 48 hours.

**Comment by ONEONUORA** [comment] 2024-12-05 13:53
Can i take this up. I am a full stack developer. ETA 24 hours

**Comment by aurlic** [comment] 2024-12-05 21:54
I would be happy to be assigned to this issue and think that I could do a good job !
I already worked on some frontent projects and think that this would be a good fit for my skills. Thanks in advance !

**Comment by PrathamJha1** [comment] 2024-12-07 18:05
Can I start working on this?

**Comment by ryzen-xp** [comment] 2024-12-08 09:20
Hi,
 I am proficient Blockchain developer  expert in web development.
I have  contributed many stark net project and more  . 
 please /assign  this issue .
Thank You

**Comment by davedumto** [comment] 2024-12-09 02:33
Hello my name is Dumto, I am a frontend developer, I am a new contributor to Only Dust and this project and I would love to work on this issue. Please can I be assigned?. ETA 1 day

**Comment by Uyouyou** [comment] 2024-12-09 21:58
Hello, I'd love to work on this issue. Can i be assigned to this?

**Closed as completed** 2024-12-14 18:28 UTC
Labels: open for contribution, Good first issue
