### ISSUE TITLE
Option " To claim " is not working properly for Boost Quest's 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#814] opened 2024-08-13 07:45 UTC
**DEMONSTRATION**
https://www.loom.com/share/f4bbb040a1e94f8f8ce1b69dd2e7a5b3?sid=ab2098dc-7db6-4bc4-875c-1dcd2a37e2f1

**Comment by Ugo-X** [comment] 2024-08-13 09:00
Please can I be assigned this issue @revengexd @fricoben

**Comment by od-hunter** [comment] 2024-08-13 09:25
Hi @revengexd , can I work this this ASAP?

**Comment by Jemiiah** [comment] 2024-08-13 10:03
can I work on this issue @fricoben

**Comment by CollinsC1O** [comment] 2024-08-18 22:36
@fricoben i will love to work on this

**Comment by GoSTEAN** [comment] 2024-08-19 08:48
@fricoben Can I work on this?

**Comment by Ayoazeez26** [comment] 2024-08-22 07:42
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a web developer with over 6 years experience building applications both personal and professional projects. I started contributing to open source via onlydust in march this year and I have contributed to a couple of issues, you can see them in my profile.

### How I plan on tackling this issue
Reproduce the bug and figure out why to claim is not being accessible

**Comment by MatiasAchucarro** [comment] 2024-08-22 07:55
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

This will be my first contribution to the open-source ecosystem, and I am excited to learn and collaborate on innovative projects, particularly those involving Cairo.

**Comment by MatiasAchucarro** [comment] 2024-08-22 07:56
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

This will be my first contribution to the open-source ecosystem, and I am excited to learn and collaborate on innovative projects, particularly those involving Cairo.

### How I plan on tackling this issue
to address the issue with the "Claim" option not working correctly in Boost Que, I would start by checking the code related to this feature to find any errors or issues in the logic. I would look at error messages or logs to get clues about what might be going wrong. Then, I’d test the feature under different conditions to reproduce the problem and understand it better. Once I identify the root cause, I’d make the necessary fixes and retest the "Claim" option to ensure it works as expected.

**Comment by Ugo-X** [comment] 2024-08-22 08:14
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

**Comment by josephchimebuka** [comment] 2024-08-22 08:44
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello @fricoben I am Joseph Chimebuka I'm a full-stack software developer with 4+ years of experience in crafting innovative products. I've built a range of projects, including https://mattedsgn.vercel.app/ and https://metacrypt.vercel.app/ showcasing my expertise in React, Next.js, and blockchain technologies. I'm also an active contributor onlydust. here's my account https://app.onlydust.com/u/josephchimebuka.

### How I plan on tackling this issue
I'll review the routing setup to ensure the path for the claim page is correctly defined in my code.  I'll inspect the link or button that leads to the claim page to ensure it's pointing to the correct URL. I will look at the console or server logs for any errors that might be preventing access to the claim page and address them accordingly.

**Comment by CollinsC1O** [comment] 2024-08-23 12:23
Hi @revengexd  I already worked on this and created a pull request. Please review and let me know if any additional changes are required.

**Comment by Marchand-Nicolas** [comment] 2024-08-25 06:56
https://github.com/starknet-id/starknet.quest/pull/827

**Closed as completed** 2024-08-26 09:40 UTC
Labels: 🚨 Small bug
