### ISSUE TITLE
Fix duplicate tasks in the admin dashboard

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#985] opened 2024-12-13 20:48 UTC
## Description 📹

**In the admin dashboard, when the "Save all tasks" button is clicked in `TaskDetailsForm.tsx`, tasks are successfully saved. However, if the user navigates back to the task tab and clicks "Save all tasks" again without refreshing the page, all tasks are duplicated. This issue is likely related to state management in the quest creation (`app/admin/quests/create/page.tsx`) and quest editing (`app/admin/quests/dashboard/[questId]/page.tsx`) components.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:

   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   - [ ] Investigate the root cause of task duplication in `TaskDetailsForm.tsx`:
     - Review how the `steps` state is being updated and passed to the save logic.
     - Ensure that `steps` are not being appended redundantly during subsequent saves.
   - [ ] Update the `handleCreateTask` method in `app/admin/quests/create/page.tsx`:
     - Add a mechanism to prevent the re-saving of tasks that have already been saved (e.g., by filtering based on task IDs or a flag indicating saved status).
     - Example:
       ```typescript
       const unsavedSteps = steps.filter((step) => !step.data.id);
       ```
   - [ ] Update the `handleTaskChanges` method in `app/admin/quests/dashboard/[questId]/page.tsx`:
     - Verify that duplicate tasks are not being added when saving updates to an existing quest.
   - [ ] Add validation to ensure that tasks are not submitted twice without clearing or refreshing their state.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:

   ```bash
   git commit -m "Fix: Prevent task duplication when 'Save all tasks' is clicked multiple times"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Benjtalkshow** [comment] 2024-12-13 20:49
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 2days.

**Comment by lauchaves** [comment] 2024-12-13 20:49
Hey I'm Lau Chaves from dojo coding Costa Rica Id like to work on this 

I have over 5 years working with react ts ruby etc 

I'd make sure I'll follow all the steps mentioned above and that it works as expected

**Comment by Michaelkingsdev** [comment] 2024-12-13 20:50
@Marchand-Nicolas 
Can i handle this task please?

**Comment by obacollins-lab** [comment] 2024-12-13 21:00
Is it okay if I tackle this?
ETA 5 hrs

**Comment by Emmanex01** [comment] 2024-12-13 21:02
Hi, I'm Emmanuel Tochukwu, a software developer. I have experience building projects with Cairo, Typescript, JavaScript, Tailwindcss and Reactjs. I would appreciate it given the opportunity to contribute to this issue.

**Comment by wheval** [comment] 2024-12-13 21:03
Hello @fricoben, 

Can I work on this?
I would investigate the bug and fix it properly.

ETA is 1 day.

**Comment by BigBen-7** [comment] 2024-12-13 21:23
Hello @fricoben,

Can I work on this?

ETA is 1 day

**Comment by Supa-mega** [comment] 2024-12-13 21:35
Hi , please Can I handle this task? first time time contributor 🙏🏿

**Comment by Jagadeeshftw** [comment] 2024-12-13 21:36
Is it okay if I take this?

**Comment by jahrulezfrancis** [comment] 2024-12-13 22:36
I’m interested in tackling the task to prevent task duplication in the admin dashboard when "Save all tasks" is clicked multiple times. From the description, it seems the issue stems from redundant state updates in TaskDetailsForm.tsx and related components.

I plan to investigate how the steps state is managed, ensure tasks are not appended redundantly, and add validations to prevent double submissions. My experience with React state management and debugging similar issues makes me confident I can resolve this efficiently. 
I can have it ready within 24 to 36 hours

**Comment by AnoukRImola** [comment] 2024-12-14 00:12
Hello @Marchand-Nicolas!

My name is Anouk Rímola, and I’m a Frontend Developer. I’m very skilled at debugging, and I haven’t made any contributions to this project yet.

Could I take this issue? :)

**Comment by Agbeleshe** [comment] 2024-12-14 00:30
Can I take this from here? ETA within 24hours thank you.

**Comment by 0xDeon** [comment] 2024-12-14 00:41
I’d like to resolve this.

I am confident in my ability to get this task done strictly following all project requirements and guidelines. Ty

**Comment by pheobeayo** [comment] 2024-12-14 01:02
Mind if I try this one?

**Comment by ryzen-xp** [comment] 2024-12-14 05:02
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by Amarjeet325** [comment] 2024-12-14 06:04
Could I take on this issue?

**Comment by Nityam573** [comment] 2024-12-14 06:06
Can I handle this task?

**Comment by sonkiee** [comment] 2024-12-14 06:14
Can I be assigned to this?

**Comment by davedumto** [comment] 2024-12-14 06:14
Hi,
My name is David, and I am a frontend developer skilled in React.js, TypeScript, and Next.js. As a new contributor, I’m eager to investigate and resolve the task duplication issue in TaskDetailsForm.tsx.
I’ll review the state management in page.tsx files, update the save logic to prevent duplicates, and test thoroughly to ensure the issue is resolved within ETA 3 days.

Looking forward to contributing!

**Comment by psychemist** [comment] 2024-12-14 07:16
Hello, StarknetQuest project maintainers! 
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive experience building backend systems, implementing user authentication, and serving web resources over a fully fleshed-out and documented API. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

Over my years of experience, I have worked with tools like:

Web3: Solidity and Rust
Backend: Express.js, Nest.js, Django, FastAPI, and Flask
Frontend: HTML/CSS, JavaScript/TypeScript, , React.js, Next.js, TailwindCSS, and shadcn/ui

Here is how I would solve this issue:

- First, iIwould examine the root cause of task duplication in TaskDetailsForm.tsx by analyzing how the steps state is managed and passed to the save logic. I willl pay extra attention to ensure that tasks are not being added during repeated saves.
- Then, I will adjust the handleCreateTask method in app/admin/quests/create/page.tsx to exclude tasks that are already saved. I will filter the steps array to include only unsaved tasks, such as those without an ID or a saved flag.
- Next, I will update the handleTaskChanges method in app/admin/quests/dashboard/[questId]/page.tsx to verify that duplicate tasks are not being added when saving changes to an existing quest. I will also implement validation to block duplicate task submissions unless their state is reset or refreshed.
- Afterward, I shall write tests to check that tasks are not duplicated and review and adjust any related code to support the updated TaskDetailsForm component and adhere to the codebase conventions.

 I aim to complete this task within 48 hours being assigned and setting up my development environment, with my first pull request submitted before 24 hours have elapsed. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀

**Comment by helios492** [comment] 2024-12-14 08:11
Hello! @Marchand-Nicolas 
As an experienced fullstack and blockchain developer, I am sure that I can satisfy you with this issue.
I am proficient in state management and also have strong background in problem solving skills.
I can handle this project within 3 business day and you will get what you want.
Thank yo for considering my opportunity and will look forward to your contact.
Best Regards.

**Comment by omsant02** [comment] 2024-12-14 08:22
I would like to work on this issue

My approach

-In create/page.tsx, I'll modify handleCreateTask to track saved task IDs and filter out already processed tasks before saving
-In dashboard/[questId]/page.tsx, I'll update handleTaskChanges to properly differentiate between new, updated and existing tasks using task IDs
-Will add step state validation in TaskDetailsForm.tsx to prevent duplicate submissions

ETA : 1 day

**Comment by Ekene001** [comment] 2024-12-14 08:52
Is it okay if I take this?

**Comment by 1nonlypiece** [comment] 2024-12-14 09:20
Can I take care of this issue?

**Comment by Crosstons** [comment] 2024-12-14 09:48
May I take care of this?

**Comment by 3th-Enjay** [comment] 2024-12-14 11:08
I've gor through the code and I can handle this eta 24 hrs

**Comment by mimisavage** [comment] 2024-12-14 11:15
I'd like to handle this task.

**Comment by caxtonacollins** [comment] 2024-12-14 11:22
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Cairo.

I will like to take care of this. Will follow the above requirements and create a good PR within 24hours.

**Comment by Marchand-Nicolas** [comment] 2024-12-17 18:32
Hello @AnoukRImola  are you working on the issue ? Please keep me informed not to be unassigned

**Comment by AnoukRImola** [comment] 2024-12-17 18:46
> Hello @AnoukRImola are you working on the issue ? Please keep me informed not to be unassigned

Hello sir! 😊

Yes, I am working on this issue, I will have the PR ready by tomorrow at the latest 🫡

**Closed as completed** 2024-12-22 09:16 UTC
Labels: open for contribution
