### ISSUE TITLE
Add a `disabled` checkbox to the quest settings

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#839] opened 2024-09-21 08:45 UTC
## Description
Add a `disabled` checkbox to the quest settings in the admin dashboard, in `components\admin\formSteps\QuestDetailsForm.tsx`. You can check the `CreateQuest` and `UpdateQuest` types: this field is already completly implemented, all we need to do is to show the actual checkbox and update questInput (which is the following type: `CreateQuest | UpdateQuest`) when the checkbox is ticked or unticked.

## PROPOSED TODO

- [ ] After all the fields (TextInputs, DateInput), simply add a new field by reusing the code of the other fields, just replace the `<TextInput` or `<DateInput` by

```html
<input type="checkbox" name=”disabled” onChange={handleQuestInputChange}>
```

![image](https://github.com/user-attachments/assets/70bebc8e-9a7c-40b8-80b0-c098133825f3)

**Comment by ShantelPeters** [comment] 2024-09-21 08:46
Hi @Marchand-Nicolas i will like to work on this kindly assign

**Comment by Jemiiah** [comment] 2024-09-21 08:58
I have previously contributed to this repository and have over 50+ contributions would love to work on this issue @Marchand-Nicolas here’s my only dust profile : https://app.onlydust.com/u/Jemiiah

**Comment by martinvibes** [comment] 2024-09-23 18:25
hello @Marchand-Nicolas please let me work on this issue by the time the od-hack starts :)

**Comment by Luluameh** [comment] 2024-09-24 02:56
Hello @Marchand-Nicolas  
 I’m excited to apply for the task of adding a disabled checkbox to the quest settings in the admin dashboard. After reviewing the task requirements, I believe I am well-equipped to handle this with precision.

**Comment by vickiddev** [comment] 2024-09-25 17:07
hello @dmirgaleev i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by vestor-dev** [comment] 2024-09-26 06:02
hello @Marchand-Nicolas can i hop on this and get it done this will be my first time contributing to this repo

**Comment by sebas11042** [comment] 2024-09-26 07:04
To add the disabled checkbox in QuestDetailsForm.tsx, I plan to reuse the structure of the existing fields, adding an <input type="checkbox" name="disabled"> after the current fields. I will implement the update of questInput in handleQuestInputChange to reflect the checkbox state.

I’m an advanced computer science student with knowledge in React and TypeScript, and I have experience working with various front-end frameworks. I’m a member of the DOJO Coding community here in CR. I plan to propose changes based on this idea, ensuring that the new checkbox integrates seamlessly with the existing form structure and improves user interaction.

Thanks!

**Comment by bitfalt** [comment] 2024-09-26 07:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hii! My name is Daniel, I’m a Computer Science student and web3 developer. I’ve done some contributions, finished a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings and I have participated in multiple Hackathons in which I learned more about TypeScript. I’m also a member of the Dojo Coding community. I’ve contributed to the project in the past regarding the api repository.

### How I plan on tackling this issue
I would approach this issue in the following way:
- Go to `components/admin/formSteps/QuestDetailsForm.tsx`
- Add the new field by using the already implemented code in the `CreateQuest` and `UpdateQuest` types
- Check for proper behaviour by running the frontend and making sure the field appears
- I would ask the maintainers if any questions come up during my implementation.

**Comment by PoulavBhowmick03** [comment] 2024-09-26 07:39
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I will address this issue by adding a disabled checkbox to the quest settings in QuestDetailsForm.tsx. I'll start by reusing the existing field components, ensuring consistency with other form elements. Specifically, I'll add:

jsx
Copy code
<input type="checkbox" name="disabled" onChange={handleQuestInputChange} />
This checkbox will be placed after all the existing TextInput and DateInput fields. I'll also ensure that questInput is updated accordingly when the checkbox is ticked or unticked, leveraging the handleQuestInputChange function. Finally, I’ll test the form to confirm that the CreateQuest and UpdateQuest types handle the disabled state correctly.
ETA - 2 days

**Comment by PoulavBhowmick03** [comment] 2024-09-26 07:39
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I will address this issue by adding a disabled checkbox to the quest settings in QuestDetailsForm.tsx. I'll start by reusing the existing field components, ensuring consistency with other form elements. Specifically, I'll add:

```jsx
<input type="checkbox" name="disabled" onChange={handleQuestInputChange} />
```
This checkbox will be placed after all the existing TextInput and DateInput fields. I'll also ensure that questInput is updated accordingly when the checkbox is ticked or unticked, leveraging the handleQuestInputChange function. 
Finally, I’ll test the form to confirm that the CreateQuest and UpdateQuest types handle the disabled state correctly.

ETA - 2 days

**Comment by mariocodecr** [comment] 2024-09-26 07:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hii! My name is Mario Araya, I’m a Software Engineer and Web3 Developer. I’ve done some contributions, finished a Starknet Bootcamp, completed exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community.


### How I plan on tackling this issue
I would approach this issue in the following way:

Navigate to components/admin/formSteps/QuestDetailsForm.tsx.
Add the disabled checkbox field by reusing the code for other input fields such as <TextInput> or <DateInput>. In this case, I would replace those with <input type="checkbox" name="disabled" onChange={handleQuestInputChange}>.
Ensure that the questInput state (which can be either CreateQuest or UpdateQuest) is updated when the checkbox is ticked or unticked, handling the change with handleQuestInputChange.
After implementing the change, I would run the frontend and verify that the checkbox appears in the quest settings and behaves correctly when toggled.
If I encounter any uncertainties during implementation, I would reach out to the maintainers for guidance.

**Comment by MatiasAchucarro** [comment] 2024-09-26 07:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, and C# with .NET Entity Framework, among others. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration. I have already made a contribution to Starknet Quest, and I am eager to take on more opportunities

### How I plan on tackling this issue
To add the "disabled" checkbox in QuestDetailsForm.tsx, I open the file and insert the checkbox input after the existing fields. I ensure that the questInput object includes the disabled field in both the CreateQuest and UpdateQuest types. In the change handler function, I update the questInput state to reflect the checkbox state. Finally, I verify that the checkbox displays correctly and that the questInput state updates when the checkbox is checked or unchecked.

**Comment by DiegoB1911** [comment] 2024-09-26 07:45
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience, primarily in Next.js. I'm also an active member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies. I'm enthusiastic about learning, contributing, and becoming a part of this project.

### How I plan on tackling this issue
To solve this issue, I would:

1. Follow your proposal: I would replace <TextInput /> or <DateInput /> with <input type="checkbox" name="disabled" onChange={handleQuestInputChange} />.

2. Ensure functionality: I will verify that everything works correctly after making the changes.

**Comment by deeseeker** [comment] 2024-09-26 08:18
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I'm Qudus Adeyemi, a frontend developer with 2 years of experience in React, Typescript and Javascript. I had the opportunity to contribute to the previous OD Hackathon, where I improved the Starknet React documentation and developed a useWatchAssets hook to enhance wallet tracking functionalities. I enjoy learning and tackling new challenges, and I see this issue as a great way to deepen my understanding of Web3 technologies while contributing to the Starknet Quest project.

For issue #839, I estimate it will take around 1-2 days to complete, and I'm excited to dive into the task and collaborate with the team!

### How I plan on tackling this issue
This is how I would tackle this issue:

Clone the project on my local machine and ensure it runs by following the provided documentation.
Review the codebase to understand its structure and locate the issue in components\admin\formSteps\QuestDetailsForm.tsx
Leverage my previous experience and follow the steps highlighted to solve the problems to address the problem.
Implement the fix based on my findings and knowledge.
Test thoroughly to ensure the issue is resolved.
Document the solution.

**Comment by GideonBature** [comment] 2024-09-26 08:23
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Software Engineer with experience in JavaScript, TypeScript, Rust, Cairo and NodeJS. I have worked with ReactJS framework as well and built several projects using it. I am also an open source contributor and made my first contribution in the ODHack #7.0 which was successfully merged.

### How I plan on tackling this issue
I will simply create a function called handleQuestInputChange if it is not already existing, and then go ahead to implement the PROPOSED TODO by adding the checkbox input type which can be used to change the state of the input.

**Comment by Benjtalkshow** [comment] 2024-09-26 08:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi @Marchand-Nicolas,

 I’m Benjamin, a JavaScript developer with four years of experience and over 18 contributions on OnlyDust | https://app.onlydust.com/u/Benjtalkshow. I’m reaady to tackle this issue   because I have a little idea to improve the quest settings in the admin dashboard.

### How I plan on tackling this issue
I’d like to add a disabled checkbox to the QuestDetailsForm.tsx file in components\admin\formSteps. The cool part is that the CreateQuest and UpdateQuest types already support this functionality, so we’re almost there. We just need to show the checkbox and make sure it updates the questInput whenever it’s checked or unchecked.

To get this done, I can simply insert the checkbox right after the existing fields (like TextInputs and DateInputs). I'll just swap out the <TextInput> or <DateInput> with <input type="checkbox" name="disabled" onChange={handleQuestInputChange}>. This will keep everything consistent and tidy.

**Comment by martinvibes** [comment] 2024-09-26 08:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
hello i am a frontend developer and a blockchain dev
please can i work on this issue :)
i would love to be a contributor on this repo


### How I plan on tackling this issue
this issue is easy to tackle please kindly assign

**Comment by od-hunter** [comment] 2024-09-26 08:58
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
HI, please can I be assigned please? I am a blockchain developer with experience in html, css, react, JavaScript,TypeScript and solidity, python and Cairo. I believe with my experience I can tackle this issue.

### How I plan on tackling this issue
To solve this issue, I’d take the following steps:
1.⁠ ⁠I’ll locate the quest settings in components\admin\formSteps\QuestDetailsForm.tsx.
2.⁠ ⁠⁠Add a checkbox after the existing fields (e.g., TextInput, DateInput), using the following: <input type="checkbox" name="disabled" onChange={handleQuestInputChange} />
3.⁠ ⁠⁠Handle updates to the questInput (which is of type CreateQuest | UpdateQuest) when the checkbox is ticked or unticked.
4.⁠ ⁠⁠Reuse existing field code for consistency, replacing <TextInput> or <DateInput> with the checkbox.

Please assign me, I’m ready to work.

**Comment by Agbeleshe** [comment] 2024-09-26 09:19
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a full stack developer with 3 years experience in HTML, CSS JavaScript, node.js React, Typescript and other libraries and frameworks .


### How I plan on tackling this issue
i will really love this to be my first contribution please :) 
i  will follow the description step by step and fix the issue.

**Comment by SoarinSkySagar** [comment] 2024-09-26 09:21
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
GM, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. You can see my projects and contributions to some major repos on my GitHub profile. The tech stack I use mainly includes Solidity, Rust, JavaScript and Typescript. I am also contributing to the Starknet and Rust ecosystems and building on Cairo and Rust languages. I am interested in contributing to projects like this to learn more about these technologies and help make these projects better. Please assign me as I would be really glad to be a contributor in this project! :)

### How I plan on tackling this issue
Hi @Marchand-Nicolas, I would:
- add this checkbox to the components\admin\formSteps\QuestDetailsForm.tsx:
```
<input type="checkbox" name=”disabled” onChange={handleQuestInputChange}>
```

### Tasks:
- [ ] Add checkbox

## ETA: 1 Hour

**Comment by Benjtalkshow** [comment] 2024-09-26 18:52
@Marchand-Nicolas Thanks. will begin working asap

**Closed as completed** 2024-09-29 11:02 UTC
Labels: 🍒 Nice to have, Good first issue
