### ISSUE TITLE
Non-Functional Connect Button

### ISSUE THREAD

**Issue by MullerTheScientist** [starknet-id/starknet.quest#771] opened 2024-07-30 19:28 UTC
**Describe the bug**
The "Connect" button, intended to display a drop-down menu of available wallets to connect to, it is not functional.

**To Reproduce**

1. Go to https://starknet.quest/
2. Click on the "Connect" button.
3. Observe the button's behavior

**Priority Level**
High - This issue prevents users from connecting their wallets, effectively blocking access to core functionality.

**Expected behavior**
The "Connect" button should display a drop-down menu listing available wallets to connect to, such as Braavos, or others.

**Actual behavior**
The "Connect" button does not respond and does not display the expected drop-down menu.

**Screenshots**
https://github.com/user-attachments/assets/b78b20ba-9d16-40b7-8993-4684b19171cc

**Desktop**
- Windows 11 pro
- Microsoft Edge
- Version 126

**Additional context**
This issue may be related to JavaScript errors, CSS styling, or wallet integration problems. Further investigation is required to determine the root cause.

**Comment by Iwueseiter** [comment] 2024-07-30 19:29
Hi can I work on this?

**Comment by Jemiiah** [comment] 2024-07-30 19:30
I would love to work on this issue @MullerTheScientist 🚀🚀

**Comment by ShantelPeters** [comment] 2024-07-30 19:42
@MullerTheScientist  can I be assigned to this .

**Comment by fricoben** [comment] 2024-07-31 08:40
It's working for me. 

Show me a video a the button not working pls

**Comment by Ugo-X** [comment] 2024-07-31 09:08
Hello Project Lead! I'm Ugo, a full-stack (js,React,Node,Next.js,Three.js,nest.js) developer with a strong track record in OD  projects. I've been actively involved since Edition 1 of OD hack, contributing to various initiatives.
Having used OnlyDust extensively, I'm confident in my ability to tackle new challenges.
I'm eager to leverage my skills and experience to contribute effectively.
my profile link: https://app.onlydust.com/u/Ugo-X

**Comment by MullerTheScientist** [comment] 2024-07-31 09:16
Hello @fricoben 
I attached a video to the bug report

**Comment by MullerTheScientist** [comment] 2024-07-31 09:18
> It's working for me.
> 
> Show me a video a the button not working pls

Here: https://github.com/user-attachments/assets/b78b20ba-9d16-40b7-8993-4684b19171cc

**Comment by MullerTheScientist** [comment] 2024-07-31 10:56
@fricoben This issue has not been addressed

**Comment by adrianvrj** [comment] 2024-08-02 17:57
Hi, is this open for contribution?
If so, can I work on it?

**Comment by fricoben** [comment] 2024-08-07 08:55
impossible to reproduce

**Closed as completed by fricoben** 2024-08-07 08:55 UTC
