### ISSUE TITLE
Add privacy icon

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#878] opened 2024-10-14 15:51 UTC
![image](https://github.com/user-attachments/assets/efeb1784-c769-45fb-83f8-9f4479b936d0)

Figma : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=5992-2550&t=dvRbR5qAwsX8KioR-1

By clicking on the privacy icon, all numbers become hidden.

**Comment by martinvibes** [comment] 2024-10-16 20:03
hello @Kevils please I would love to work on this issue

**Comment by lauchaves** [comment] 2024-10-24 07:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, Im part of Dojo Coding Costa Rica! I would like to contribute to this issue!

I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby...

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous self- QA processes. I have a solid knowledge of CSS, Sass, and styled-components.


### How I plan on tackling this issue
I would add the privacy icon and I would do a toggle function to use it on the icon so we can show/hide the amount with **** so it looks as the design provided!

If needed I can make this a reusable component something like 

<DynamicAmount amount={10500} />

Also if needed we can receive it as a string already in $ format 

<DynamicAmount amount={"$10.500.00"}

**Comment by martinvibes** [comment] 2024-10-24 07:14
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
please kindly assign

**Comment by diegoTech14** [comment] 2024-10-24 07:20
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello @Kevils

I'm a software engineer from Costa Rica and a proud member of Dojo Coding. I've contributed to projects like Go Stark Me, Coffiblocks, and DipDup, and I have experience with technologies such as JavaScript, Node.js, CSS, React, C#, and Cairo. I would love the opportunity to help with this issue and contribute to your project.

### How I plan on tackling this issue
For this issue I will:

`1.` I will add the privacy icon to show and hide the (*) characters
`2.` I will ensure that the UI aligns with the Figma design
`3.` Tests: I will make some manual tests to ensure that everything is okay clicking the privacy icon

Looking forward to your feedback!

Best regards,


Diego Duarte Fernández.

**Comment by joeperpetua** [comment] 2024-10-24 07:22
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
3+ years full stack dev

**Comment by zleypner** [comment] 2024-10-24 08:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
 continue making contribution to this project and contribute to the project's success.
I'm also a member of the Dojo Coding community CR.


### How I plan on tackling this issue
I would create the privacy icon that triggers a toggle function to show or hide the amounts, so it shows as **** when hidden. Based on the design requested.

**Comment by 0xDeon** [comment] 2024-10-24 08:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Good day, I’m Deon, I’m a Full stack web3 developer with a strong passion for creating intuitive and user-friendly interfaces.

I have experience in modern JavaScript frameworks and a keen eye for design, which allows me to effectively translate design concepts into functional web applications. I’m dedicated to enhancing user experiences and continuously learning about best practices in frontend development.

### How I plan on tackling this issue
- Review Figma Design: Open the provided Figma link and examine the privacy icon design and its intended functionality.

- mplement Icon in UI: Integrate the privacy icon into the existing user interface. Ensure that it aligns with the overall design and follows any relevant design guidelines.

- Add Click Functionality: Implement the click event for the privacy icon. When clicked, it should toggle the visibility of all numbers within the specified context (e.g., hiding or revealing them).

- State Management: Ensure that the state of the numbers (visible or hidden) is managed effectively, possibly using local component state or a context provider, depending on the application's architecture.

- Testing: Conduct thorough testing to ensure that the icon behaves as expected. Verify that clicking the icon correctly hides and shows the numbers and that there are no unintended side effects.

- Accessibility Considerations: Ensure that the icon is accessible, providing appropriate alt text and keyboard navigation support.

- Documentation: Update any relevant documentation or comments in the codebase to describe the new functionality and how to use the privacy icon.

- Create a Pull Request: Once the implementation is complete and tested, submit a pull request detailing the changes and their purpose.

**Comment by Benjtalkshow** [comment] 2024-10-24 08:27
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will add a privacy icon to the UI, allowing users to toggle the visibility of sensitive information, such as numbers. When clicked, the privacy icon will hide all numbers on the page, replacing them with placeholders or a hidden symbol. I will ensure the functionality works across different sections of the app, and the numbers will remain hidden until the user clicks the icon again to reveal them. The implementation will be smooth and intuitive, enhancing user privacy control.

**Comment by SudiptaPaul-31** [comment] 2024-10-24 08:34
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello! I’m Sudipta Paul, and I currently have 1.5 years of experience in the field of blockchain and web development. I'm eager to contribute to the implementation of the privacy icon as outlined in this issue.

### How I plan on tackling this issue
My approach to solve this issue: 
I will start by analyzing the Figma design to understand the specifications and styling of the privacy icon.
 will add the privacy icon to the relevant component, ensuring it matches the design provided in Figma.
The code snippet may look like this to integrate the solution 
const NumbersDisplay = ({ numbers }) => {
    const [isHidden, setIsHidden] = useState(false);

    const toggleVisibility = () => {
        setIsHidden(!isHidden);
    };

    return (
        <div>
            <PrivacyIcon onClick={toggleVisibility} />
            <ul>
                {numbers.map((number, index) => (
                    <li key={index}>
                        {isHidden ? '••••' : number}
                    </li>
                ))}
            </ul>
        </div>
    );
};
The above code includes a PrivacyIcon component that, when clicked, toggles the visibility of the numbers. It will display •••• when hidden and the actual numbers when visible.
After adding the icon and functionalityI will test to ensure that clicking the icon successfully hides and reveals the numbers as intended.

**Comment by dahtee** [comment] 2024-10-24 08:45
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm a frontend and smart contract developer and I'd be happy to contribute to this project as this will
be my first time contributing to this project.  I'm good with React, nextJS, tailwind, typescript and javascript for frontend.

### How I plan on tackling this issue
Here is my approach to tackle this issue:
1. I will look at the code base to understand and also identify where I'm expected to implement the logic.
2. I will add a state to track whether the numbers should be visible or hidden using React’s 
`useState` to toggle between showing and hiding numbers.
3. I will ensure the logic is working as expected.


ETA: 24hrs.

**Comment by ridwanalaps** [comment] 2024-10-24 09:21
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a frontend developer with 2 years experience building applications, this is my first contribution to starknet quest

### How I plan on tackling this issue
I would add the icon and implement toggle for it to hide the numbers and display a password pattern

**Comment by ryzen-xp** [comment] 2024-10-24 09:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack Blockchain developer skilled in Cairo, Solidity, Rust, and Web2 technologies. I’ve contributed to projects like Worldcoin-Bridge-Linea and ARK Project NFTs Bridge.

### How I plan on tackling this issue
I see this figma : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=5992-2550&t=dvRbR5qAwsX8KioR-1
Here is my approch for this ----->
[1]=>Add a click event to the privacy icon to toggle number visibility.
[2]=>Replace numbers with placeholders (e.g., ****) when hidden.
[3]=>Use a state variable to track and persist the visibility status.
[4]=>Test and integrate the feature with the existing design.
[5]=>Sir please assign me

**Comment by Villarley** [comment] 2024-10-24 11:45
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am Santiago Villarreal Arley, a passionate software developer with a growing interest in Web3 technologies. Over the past few months, I've had the opportunity to work on innovative projects, such as BuildMyEvent, an open-source initiative that leverages blockchain and decentralized systems. I thrive on problem-solving and enjoy the challenge of integrating cutting-edge solutions into real-world applications. My goal is to contribute to the Web3 ecosystem by staying ahead of emerging trends, learning continuously, and developing projects that push the boundaries of decentralized technologies.



### How I plan on tackling this issue
To tackle the "Portfolio by protocol used" section, here’s my proposed solution:

Donut Chart Implementation:

I would utilize a charting library like Chart.js or Recharts to create a clean and interactive donut chart. The chart would dynamically display the portfolio distribution based on protocols used.
The data could be fetched via an API or passed as props, ensuring each protocol is visually represented as a segment of the donut chart with its corresponding percentage of use.
"Claim your reward" Button:

The button will be positioned below the chart, styled according to the Figma design.
On click, it will trigger an action to claim the user’s reward, which can involve calling an API or handling any necessary authentication flow.
I’ll make sure to include visual feedback (loading indicator, success confirmation) to provide a smooth user experience.
Design & Layout:

I’ll strictly follow the Figma design to match the overall layout and feel of the project, ensuring responsiveness and consistency.
Using Tailwind CSS (or the project's current styling approach), I’ll maintain a clean, scalable layout.
Testing and Feedback:

I would ensure the chart is responsive and that the "Claim your reward" button is functional and user-friendly.
Proper integration with the backend will be key for a seamless reward claim process.
I look forward to contributing to this feature and bringing it to life as part of the Starknet.quest project!

**Comment by aniruddhaaps** [comment] 2024-10-24 12:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by LazarusAA** [comment] 2024-10-24 12:42
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm Alvaro Lazarus a passionate Blockchain developer and a new member of Dojo Coding with experience with Python,  TypeScript, Solidity and Cairo. Id love to contribute to this project and I think this issue could be a fun one to tackle.

### How I plan on tackling this issue
- Implement a click event on the privacy icon to toggle between showing and hiding the numbers.
- When numbers are hidden, display placeholders (****) instead of the actual values.
- Use a state variable to keep track of whether the numbers are visible or hidden.
- Test the feature thoroughly and integrate it seamlessly into the existing design.

ETA: 24 hrs

**Comment by PedroCo3lho** [comment] 2024-10-24 13:00
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have experience working on projects where I implemented new designs and integrated them with the backend. I am familiar with frameworks such as React and Next.js, and proficient in JavaScript and TypeScript.

### How I plan on tackling this issue
I would first review the current implementation to understand how can I implement the hiddenAmount function. Then, I would ensure that when the icon is clicked, the displayed values are properly hidden by updating the state on the frontend. This would involve modifying the UI state and ensuring the data is masked.

**Comment by mexes20** [comment] 2024-10-24 13:53
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello, can I be assigned to work on this issue as a first time contributor?

I'm a software developer with over 6 years experience

ETA: One day

**Comment by Marchand-Nicolas** [comment] 2024-10-24 13:54
I will assign someone after the following issues are merged:
- https://github.com/lfglabs-dev/starknet.quest/issues/880
- https://github.com/lfglabs-dev/starknet.quest/issues/879
- https://github.com/lfglabs-dev/starknet.quest/issues/877

**Comment by NueloSE** [comment] 2024-10-24 14:59
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
i am a frontend developer with experience in developing frontend user responsive web pages.

### How I plan on tackling this issue
looking at the figma design all i need to do is import the icon from material ui and implement the required desired to hide user password

**Comment by mimisavage** [comment] 2024-10-24 15:37
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I’m Mimi Sav, a frontend and blockchain developer. This is my first time contributing to this repository, and I'm excited about the opportunity to collaborate.


### How I plan on tackling this issue
To tackle this task, I will first review the Figma design to understand the layout and functionality required for the privacy icon feature. I will implement an event listener for the privacy icon that, when clicked, toggles the visibility of all numerical elements on the page. This will involve adding a CSS class to hide the numbers, ensuring that the user experience remains intuitive. I will also test the functionality to confirm that clicking the icon successfully hides and reveals the numbers as intended. Finally, I will ensure the implementation is seamless across different devices and browsers for consistency.

**Comment by KevinLatino** [comment] 2024-10-24 17:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/                                                                                                

How I plan on tackling this issue                                                                                                   @Kevils @Marchand-Nicolas will have it in a few hours!  please give me the opportunity

**Comment by Kaminar-i** [comment] 2024-10-24 21:06
Can I be given the opportunity to work on this?

**Comment by jaiminRaiyani** [comment] 2024-10-25 03:07
May I be assigned to this?

**Comment by blessingbytes** [comment] 2024-10-25 06:00
I'd like to handle this task.

**Comment by ShantelPeters** [comment] 2024-10-25 07:29
I'd love to work on this!I will identify all numeric elements in the relevant component based on the Figma design. Using React's state management, I will create a state variable (isPrivate) to toggle the visibility of numbers when the privacy icon is clicked. An onClick event listener will trigger a function to toggle this state, and conditional rendering will display either the numbers or placeholders (e.g., ●●●●) accordingly. I will ensure that the UI is consistent with the Figma design through appropriate CSS styling and conduct thorough testing to confirm expected behavior across scenarios.

**Comment by DotworldX** [comment] 2024-10-25 07:53
I’m interested in this one.

**Comment by hannahredler** [comment] 2024-10-25 08:54
May I pick this up?Hi, my name is Hannah I'm a developer currently on the HerDAO Starknet Bootcamp and would love to take this issue!

## My background

About me - I have been working as a full stack developer over the past few years, with plenty of experience in Typescript, React, RxJS. a few years ago I transitioned to the web3 ecosystem building a fully responsive real time trading app in the ethereum ecosystem. I recently discovered starknet and am looking to get more involved here!

## How I would tackle the issue

- Add the required icon, when clicked it changes the react state (using react hooks) in the component to hidden/ not hidden. 
- If hidden, each icon displays as a star. If not, they display correctly.

Thanks for reading!

**Comment by ymjrcc** [comment] 2024-10-25 09:21
I’d like to help with this.

**Comment by reetbatra** [comment] 2024-10-25 09:41
I'd be happy to do this. HER DAO

**Comment by wheval** [comment] 2024-10-25 15:34
I’d like to resolve this. I would ensure that the privacy icon hides all the numbers by using a consistent hidden state, while preserving the UI. 
Hoping to get assigned. Would love to contribute to Starknet quest.

ETA is 1 day.

**Comment by Pvsaint** [comment] 2024-10-25 16:02
Can I be assigned to this?

**Comment by soomtochukwu** [comment] 2024-10-25 23:03
Would love to tackle this!

**Comment by 0xDeon** [comment] 2024-10-25 23:18
@Marchand-Nicolas I have previously applied via onlydust and would like to know if this issue is still available

**Comment by deeseeker** [comment] 2024-10-25 23:20
Could I try solving this?

**Comment by Aditya-040** [comment] 2024-10-26 05:42
Can I take care of this issue? I am a full stack developer.

**Comment by jedstroke** [comment] 2024-10-26 12:55
This will be like a breeze through the park for me

**Comment by Akshola00** [comment] 2024-10-27 13:19
Can I tackle this one?

**Comment by Dprof-in-tech** [comment] 2024-10-27 14:02
hello chief, i'm Dprof-in-tech, a returning contributor to the starknet quest project and i would love to work on this issue. My expected time of delivery is 1 day.

**Comment by vijay-kesanakurthi** [comment] 2024-10-29 09:32
Can I take care of this issue?

**Comment by mimisavage** [comment] 2024-10-29 09:35
I want to take on this issue, can I be assigned?

**Comment by tasneemtoolba** [comment] 2024-10-29 14:27
Can I try solving this issue?

**Comment by suhas-sensei** [comment] 2024-10-29 15:36
Instead of simply replacing numbers with asterisks (*) or dots (•), i will implement a blur effect that gradually increases/decreases when toggling privacy mode - preserving the approximate visual length/space of the numbers while making them unreadable. This maintains the UI layout while providing a smooth, animated transition between visible and private states. Hoping to be assigned.

**Comment by sigmadawg** [comment] 2024-10-29 22:02
im a newbie contributor, i'd be grateful if you'd give me the opportunity to work in this.

**Comment by BrunoAmbricca** [comment] 2024-10-30 13:58
Hello, I would like to do this issue please

**Comment by PabloVillaplana** [comment] 2024-10-30 15:38
I arrived late to this ODHack, I would like to contribute to this issue, to close the month with a contribution

**Comment by JosueBrenes** [comment] 2024-10-31 03:59
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take 1 day to complete.


## Solution Plan for Issue

## Overview
Implement a toggle functionality in a TypeScript React (TSX) component to show or hide sensitive information (like passwords) upon clicking an icon.

## Steps

1. **State Management**  
   Use the `useState` hook to manage the visibility of the sensitive information.
   ```tsx
   const [isHidden, setIsHidden] = useState(true);
   ```

2. **Toggle Function**  
   Create a function to toggle the `isHidden` state.
   ```tsx
   const toggleVisibility = () => {
       setIsHidden(!isHidden);
   };
   ```

3. **Conditional Rendering**  
   Display the sensitive information as masked (e.g., `******`) or visible based on the `isHidden` state.
   ```tsx
   <span>{isHidden ? '******' : info}</span>
   ```

4. **Icon and Styling**  
   Include an eye or eye-off icon for toggling visibility. Use a click event on the icon to call the `toggleVisibility` function.

5. **Sample Code**  
   Here’s an example of the component:

   ```tsx
   import React, { useState } from 'react';
   import { FaEye, FaEyeSlash } from 'react-icons/fa';

   const SensitiveInfoToggle: React.FC<{ info: string }> = ({ info }) => {
       const [isHidden, setIsHidden] = useState(true);

       const toggleVisibility = () => {
           setIsHidden(!isHidden);
       };

       return (
           <div>
               <span>{isHidden ? '******' : info}</span>
               <button onClick={toggleVisibility}>
                   {isHidden ? <FaEye /> : <FaEyeSlash />}
               </button>
           </div>
       );
   };

   export default SensitiveInfoToggle;
   ```

6. **Expected Outcome**  
   - The icon toggles the information between hidden (masked) and visible states when clicked, providing a user-friendly way to manage sensitive information visibility.

---

**Comment by Michaelkingsdev** [comment] 2024-11-01 09:04
I’d love to work on this task.

**Comment by Kingsuite** [comment] 2024-11-01 10:41
Can I be assigned to this?

**Comment by mimisavage** [comment] 2024-11-01 11:03
I would love to take this up. I like 🍒

**Comment by sasasamaes** [comment] 2024-11-02 19:48
Is this issue still available?

	1.	Examine the Figma Design:
	•	Open the Figma link and review the expected design for hidden numbers. Take note of any specific styling or icon changes when numbers are hidden.
	2.	Set Up the Component State:
	•	In your React component, add a state to track whether the numbers should be hidden or visible.


```
import { FaEye, FaEyeSlash } from 'react-icons/fa';
const [isHidden, setIsHidden] = useState(false);
const toggleVisibility = () => {
        setIsHidden(!isHidden);
};

return (
        <div>
            <span>{isHidden ? '******' : info}</span>
            <button onClick={toggleVisibility}>
                {isHidden ? <FaEye /> : <FaEyeSlash />}
            </button>
        </div>
    );

```

ETA: 1 Day

**Comment by SoarinSkySagar** [comment] 2024-11-03 03:55
I'll refactor the numbers part of the page into its own separate component, then use the useState hook to store the current state of the visibility, through a new bool variable isVisible. Then conditionally render the numbers, only if isVisible is set to true, else ***** if it's false.
ETA: 1 Day

**Comment by Marchand-Nicolas** [comment] 2024-11-03 12:24
Hello @diegoTech14 are you still available to work on this issue ?
The aim is simply to make the eye icon clickable so that it hides all numbers (wallet amount, and chart values) as shown in the figma
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/f097ed84-cfd7-4b3a-92a2-9fa59ad2f336">

Here is the closed eye icon:
```tsx
<svg xmlns="http://www.w3.org/2000/svg" width="17" height="16" viewBox="0 0 17 16" fill="none">
  <path d="M8.38797 6L10.5013 8.10667V8C10.5013 7.46957 10.2906 6.96086 9.91552 6.58579C9.54044 6.21071 9.03174 6 8.5013 6H8.38797ZM5.5213 6.53333L6.55464 7.56667C6.5213 7.70667 6.5013 7.84667 6.5013 8C6.5013 8.53043 6.71202 9.03914 7.08709 9.41421C7.46216 9.78929 7.97087 10 8.5013 10C8.64797 10 8.79464 9.98 8.93464 9.94667L9.96797 10.98C9.5213 11.2 9.02797 11.3333 8.5013 11.3333C7.61725 11.3333 6.7694 10.9821 6.14428 10.357C5.51916 9.7319 5.16797 8.88406 5.16797 8C5.16797 7.47333 5.3013 6.98 5.5213 6.53333ZM1.83464 2.84667L3.35464 4.36667L3.65464 4.66667C2.55464 5.53333 1.68797 6.66667 1.16797 8C2.3213 10.9267 5.16797 13 8.5013 13C9.53464 13 10.5213 12.8 11.4213 12.44L11.708 12.72L13.6546 14.6667L14.5013 13.82L2.6813 2M8.5013 4.66667C9.38536 4.66667 10.2332 5.01786 10.8583 5.64298C11.4834 6.2681 11.8346 7.11595 11.8346 8C11.8346 8.42667 11.748 8.84 11.5946 9.21333L13.548 11.1667C14.548 10.3333 15.348 9.24 15.8346 8C14.6813 5.07333 11.8346 3 8.5013 3C7.56797 3 6.67464 3.16667 5.83464 3.46667L7.2813 4.9C7.6613 4.75333 8.06797 4.66667 8.5013 4.66667Z" fill="#E1DCEA"/>
</svg>
```

**Comment by Jemiiah** [comment] 2024-11-03 12:26
@Marchand-Nicolas i can work on it quickly

**Comment by diegoTech14** [comment] 2024-11-03 14:50
> Hello @diegoTech14 are you still available to work on this issue ? The aim is simply to make the eye icon clickable so that it hides all numbers (wallet amount, and chart values) as shown in the figma <img alt="image" width="1345" src="https://private-user-images.githubusercontent.com/60229704/382570477-f097ed84-cfd7-4b3a-92a2-9fa59ad2f336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDU2NDgsIm5iZiI6MTczMDY0NTM0OCwicGF0aCI6Ii82MDIyOTcwNC8zODI1NzA0NzctZjA5N2VkODQtY2ZkNy00YjNhLTkyYTItOWZhNTlhZDJmMzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE0NDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YzNjODg4OWQ3NDM2ODRiMjQ4YzUwNzBiNzAzZWE3MTdjZmMxMDQyYTIyNmU5MzRjNDVkYTkxN2MwMmFkZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JfBoTF96WdbVraU9mD0FmUKoELfOuwVYez4QHLE4woY">
> 
> Here is the closed eye icon:
> 
> ```tsx
> <svg xmlns="http://www.w3.org/2000/svg" width="17" height="16" viewBox="0 0 17 16" fill="none">
>   <path d="M8.38797 6L10.5013 8.10667V8C10.5013 7.46957 10.2906 6.96086 9.91552 6.58579C9.54044 6.21071 9.03174 6 8.5013 6H8.38797ZM5.5213 6.53333L6.55464 7.56667C6.5213 7.70667 6.5013 7.84667 6.5013 8C6.5013 8.53043 6.71202 9.03914 7.08709 9.41421C7.46216 9.78929 7.97087 10 8.5013 10C8.64797 10 8.79464 9.98 8.93464 9.94667L9.96797 10.98C9.5213 11.2 9.02797 11.3333 8.5013 11.3333C7.61725 11.3333 6.7694 10.9821 6.14428 10.357C5.51916 9.7319 5.16797 8.88406 5.16797 8C5.16797 7.47333 5.3013 6.98 5.5213 6.53333ZM1.83464 2.84667L3.35464 4.36667L3.65464 4.66667C2.55464 5.53333 1.68797 6.66667 1.16797 8C2.3213 10.9267 5.16797 13 8.5013 13C9.53464 13 10.5213 12.8 11.4213 12.44L11.708 12.72L13.6546 14.6667L14.5013 13.82L2.6813 2M8.5013 4.66667C9.38536 4.66667 10.2332 5.01786 10.8583 5.64298C11.4834 6.2681 11.8346 7.11595 11.8346 8C11.8346 8.42667 11.748 8.84 11.5946 9.21333L13.548 11.1667C14.548 10.3333 15.348 9.24 15.8346 8C14.6813 5.07333 11.8346 3 8.5013 3C7.56797 3 6.67464 3.16667 5.83464 3.46667L7.2813 4.9C7.6613 4.75333 8.06797 4.66667 8.5013 4.66667Z" fill="#E1DCEA"/>
> </svg>
> ```

Hi @Marchand-Nicolas, I will start today, thank you for the opportunity! ⚡

**Comment by Marchand-Nicolas** [comment] 2024-11-04 21:14
Hello @jedstroke are you still available to work on this issue ? (Should be quick to do I think)
The aim is simply to make the eye icon clickable so that it hides all numbers (wallet amount, and chart values) as shown in the figma
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/f097ed84-cfd7-4b3a-92a2-9fa59ad2f336">

Here is the closed eye icon:
```tsx
<svg xmlns="http://www.w3.org/2000/svg" width="17" height="16" viewBox="0 0 17 16" fill="none">
  <path d="M8.38797 6L10.5013 8.10667V8C10.5013 7.46957 10.2906 6.96086 9.91552 6.58579C9.54044 6.21071 9.03174 6 8.5013 6H8.38797ZM5.5213 6.53333L6.55464 7.56667C6.5213 7.70667 6.5013 7.84667 6.5013 8C6.5013 8.53043 6.71202 9.03914 7.08709 9.41421C7.46216 9.78929 7.97087 10 8.5013 10C8.64797 10 8.79464 9.98 8.93464 9.94667L9.96797 10.98C9.5213 11.2 9.02797 11.3333 8.5013 11.3333C7.61725 11.3333 6.7694 10.9821 6.14428 10.357C5.51916 9.7319 5.16797 8.88406 5.16797 8C5.16797 7.47333 5.3013 6.98 5.5213 6.53333ZM1.83464 2.84667L3.35464 4.36667L3.65464 4.66667C2.55464 5.53333 1.68797 6.66667 1.16797 8C2.3213 10.9267 5.16797 13 8.5013 13C9.53464 13 10.5213 12.8 11.4213 12.44L11.708 12.72L13.6546 14.6667L14.5013 13.82L2.6813 2M8.5013 4.66667C9.38536 4.66667 10.2332 5.01786 10.8583 5.64298C11.4834 6.2681 11.8346 7.11595 11.8346 8C11.8346 8.42667 11.748 8.84 11.5946 9.21333L13.548 11.1667C14.548 10.3333 15.348 9.24 15.8346 8C14.6813 5.07333 11.8346 3 8.5013 3C7.56797 3 6.67464 3.16667 5.83464 3.46667L7.2813 4.9C7.6613 4.75333 8.06797 4.66667 8.5013 4.66667Z" fill="#E1DCEA"/>
</svg>
```

**Comment by 0xDeon** [comment] 2024-11-04 21:36
@Marchand-Nicolas Can i please take this issue?
I can get this done in less than 24 hrs

**Comment by jedstroke** [comment] 2024-11-04 22:58
I am wrapping up

**Comment by Marchand-Nicolas** [comment] 2024-11-05 09:15
Hello @Jemiiah  are you still available to work on this issue ? (Should be quick to do I think)
The aim is simply to make the eye icon clickable so that it hides all numbers (wallet amount, and chart values) as shown in the figma
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/f097ed84-cfd7-4b3a-92a2-9fa59ad2f336">

Here is the closed eye icon:
```tsx
<svg xmlns="http://www.w3.org/2000/svg" width="17" height="16" viewBox="0 0 17 16" fill="none">
  <path d="M8.38797 6L10.5013 8.10667V8C10.5013 7.46957 10.2906 6.96086 9.91552 6.58579C9.54044 6.21071 9.03174 6 8.5013 6H8.38797ZM5.5213 6.53333L6.55464 7.56667C6.5213 7.70667 6.5013 7.84667 6.5013 8C6.5013 8.53043 6.71202 9.03914 7.08709 9.41421C7.46216 9.78929 7.97087 10 8.5013 10C8.64797 10 8.79464 9.98 8.93464 9.94667L9.96797 10.98C9.5213 11.2 9.02797 11.3333 8.5013 11.3333C7.61725 11.3333 6.7694 10.9821 6.14428 10.357C5.51916 9.7319 5.16797 8.88406 5.16797 8C5.16797 7.47333 5.3013 6.98 5.5213 6.53333ZM1.83464 2.84667L3.35464 4.36667L3.65464 4.66667C2.55464 5.53333 1.68797 6.66667 1.16797 8C2.3213 10.9267 5.16797 13 8.5013 13C9.53464 13 10.5213 12.8 11.4213 12.44L11.708 12.72L13.6546 14.6667L14.5013 13.82L2.6813 2M8.5013 4.66667C9.38536 4.66667 10.2332 5.01786 10.8583 5.64298C11.4834 6.2681 11.8346 7.11595 11.8346 8C11.8346 8.42667 11.748 8.84 11.5946 9.21333L13.548 11.1667C14.548 10.3333 15.348 9.24 15.8346 8C14.6813 5.07333 11.8346 3 8.5013 3C7.56797 3 6.67464 3.16667 5.83464 3.46667L7.2813 4.9C7.6613 4.75333 8.06797 4.66667 8.5013 4.66667Z" fill="#E1DCEA"/>
</svg>
```

**Comment by Jemiiah** [comment] 2024-11-05 09:16
Yes I still am ser 🚀

**Closed as completed** 2024-11-08 09:45 UTC
Labels: open for contribution, Good first issue
