### ISSUE TITLE
infinite-Loop in notification status  

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#890] opened 2024-10-18 20:23 UTC
Details : https://www.loom.com/share/521d81b4bd0b4da5a0b62475454f4135

**Comment by Abeeujah** [comment] 2024-10-19 06:03
Hi, can I work on this?

**Comment by martinvibes** [comment] 2024-10-19 21:56
Hello @revengexd please let me work on this issue

**Comment by ikemHood** [comment] 2024-10-24 07:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello @revengexd, I would love to handle this issue,

From my understanding the problem happens because useEffect runs on every re-render of the app 

```ts
  useEffect(() => {
    if (notifications) {
      const fileredNotifications = notifications.filter(
        (notif: SQNotification<TransactionData>) =>
          notif.data.status === "pending"
      );
      fileredNotifications.forEach((notif) => {
        checkTransactionStatus(notif.data.hash);
      });
    }
  }, [notifications, checkTransactionStatus]);
```
and the state does not successfully updated to `success` on the store after it has been confirmed
```ts
  const checkTransactionStatus = async (txHash: string) => {
    const data = await provider.getTransactionReceipt(txHash);
    if (data?.isRejected() || data?.isReverted()) {
      updateNotificationStatus(txHash, "error");
      setUnread(true);
    } else if (data?.isSuccess()) {
      updateNotificationStatus(txHash, "success");
      setUnread(true);
    }
  };
```

I will find a better way to implement this when assigned...

**Comment by 0xDeon** [comment] 2024-10-24 08:18
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I’m a Full-Stack with a strong passion for creating intuitive and user-friendly interfaces. I have experience in modern JavaScript frameworks and a keen eye for design, which allows me to effectively translate design concepts into functional web applications. 

I’m dedicated to enhancing user experiences and continuously learning about best practices in frontend development.

### How I plan on tackling this issue
- I'll start by reviewing the code related to the notification status to pinpoint where the infinite loop is occurring. Look for any recursive calls or repeated state updates that may not have a terminating condition.

- I'll Implement logging around the notification status logic to trace execution flow and identify what conditions are leading to the loop.

- I'll then examine how the notification state is being managed and ensure that state updates are correctly conditioned to prevent continuous re-rendering or updating without changes.

- I'll add checks to ensure that the loop can exit under certain conditions. This could involve validating the status before updating or implementing a maximum retry limit.

- After implementing the changes, thoroughly test the notification system to ensure the infinite loop is resolved and that notifications behave as expected.

- Update any relevant documentation to reflect changes made to the notification status logic.

- Once testing is complete and the issue is resolved, submit a pull request detailing the changes and the reasoning behind them.

**Comment by Benjtalkshow** [comment] 2024-10-24 08:26
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will begin by investigating the logic behind the notification system, particularly focusing on why notifications are not being updated correctly when switching between pages. I'll ensure that the notification state is preserved and that any pending or new notifications are properly fetched and displayed without needing to manually click each time.

I will review the backend or API handling notifications to avoid missing data when navigating across pages. Finally, I will test thoroughly to fix the infinite loop issue, ensuring notifications appear correctly and consistently on all pages.

**Comment by NueloSE** [comment] 2024-10-24 08:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a frontend developer with experience in using Javascript typescript and react for frontend development.

### How I plan on tackling this issue
I have gone through the loom video and a psuedo approach to solving this problem would be :
I'll ensure the notification doesn’t re-trigger itself unintentionally. I’ll add conditions to prevent the same notification from being sent repeatedly.
I’ll use flags or status updates to mark when a notification has been handled to prevent re-processing.
I’ll add checks to ensure changes in status or actions don’t cause the same event to reoccur in a loop.
I’ll implement delays or intervals carefully to avoid creating unintentional loops in repeated notifications.\

**Comment by ryzen-xp** [comment] 2024-10-24 09:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full stack Blockchain developer with expertise in Cairo, Solidity, Rust, and Web2 technology . I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge and more .

### How I plan on tackling this issue
Hello ,  I see  this video  https://www.loom.com/share/521d81b4bd0b4da5a0b62475454f4135
My approch =>
[1]=>Ensure the notification doesn't unintentionally trigger itself repeatedly by adding conditions to prevent duplicate notifications.
[2]=>Use flags or status indicators to mark when a notification has been processed, preventing it from being handled multiple times.
[3]=>Implement checks to ensure status changes or actions don’t cause the event to retrigger in a loop.
[4]=>Carefully handle delays or intervals to avoid creating unintended loops or spam from repeated notifications.

**Comment by bhavyagosai** [comment] 2024-10-24 09:37
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hey, I am Bhavya, a seasoned frontend engineer with two years of professional experience. I have been working with react, react native, nextjs, typescript, shadcn, tailwindcss for a while now. Have worked previously with Starknet Quest so I am largely familiar with the codebase!

### How I plan on tackling this issue
This seems to be a state management problem where the state is being reset upon first render and not being auto updated as needed unless the component is being individually interacted with.

Should be considerably easy to fix. 

ETA should be 1 day. But if the problem is not related to frontend only then it might take longer

**Comment by suhas-sensei** [comment] 2024-10-24 10:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
i have experience in cairo and blockchain previously as personal projects and OS  and mark my first odhack contribution.

**Comment by ShantelPeters** [comment] 2024-10-24 10:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have a robust background in software development, particularly in creating and maintaining web applications. My experience includes proficiency in both front-end and back-end technologies, enabling me to understand the full stack of application development. I have worked extensively with RESTful APIs and am familiar with integrating third-party services, which is crucial for the task at hand. Additionally, my ability to analyze requirements and translate them into functional code will ensure effective problem-solving.



### How I plan on tackling this issue
 To address the issue detailed in the Loom video, I will first carefully review the content provided to understand the specific requirements and context of the problem. This will include identifying any existing functionality that needs enhancement or debugging.

Next, I will outline the necessary changes or implementations, breaking down the tasks into manageable components. If the issue pertains to API integration or data handling, I will examine the relevant codebase and identify areas where modifications are required.

After drafting a plan, I will implement the changes in a development environment, ensuring to follow best practices for coding and documentation. I will also conduct thorough testing to verify that the adjustments meet the specified requirements and that no new issues are introduced.

Finally, I will document the changes made and provide a summary of the implementation to facilitate future maintenance and updates.

**Comment by aniruddhaaps** [comment] 2024-10-24 12:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Closed as completed** 2024-10-29 11:02 UTC
Labels: 🚨 Small bug, open for contribution
