### ISSUE TITLE
Delete the `Head of art` card on the `partnership` page

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#841] opened 2024-09-23 18:16 UTC
![image](https://github.com/user-attachments/assets/646499e0-33f8-4c71-9475-82b7078f60db)

**Comment by ShantelPeters** [comment] 2024-09-23 18:16
Hi @fricoben please can I be assigned to this issue

**Comment by raizo07** [comment] 2024-09-23 18:21
@fricoben can I work on this?

**Comment by martinvibes** [comment] 2024-09-23 18:22
hello @fricoben please I would love to work on this issue :) 
ETA: 12hrs

**Comment by Luluameh** [comment] 2024-09-24 02:47
Hello @fricoben  I will love to work on this issue

**Comment by Agbeleshe** [comment] 2024-09-24 02:49
Hello, i'm interested in fixing this issue. I would love to make it my first contribution. thank you :)

**Comment by vickiddev** [comment] 2024-09-25 04:21
hello @fricoben please let me work on this issue :)

i would love to be a contributor on this repo

**Comment by vestor-dev** [comment] 2024-09-26 06:00
@fricoben let me have this issue please

**Comment by KevinMB0220** [comment] 2024-09-26 06:40
Hi, I'm Kevin from Dojo Coding, and here is how I would resolve the request to remove the "Head of art" card from the partnership page (#841): I would review the page’s code to locate the section where the card is rendered and remove or disable the relevant component. Then, I would test the changes to ensure the page retains its structure and style without any issues. Finally, I would confirm the adjustments and apply the changes to the main repository if needed. @fricoben

**Comment by bitfalt** [comment] 2024-09-26 07:25
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hii! My name is Daniel, I’m a Computer Science student and web3 developer. I’ve done some contributions, finished a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings and I have participated in multiple Hackathons. I’m also a member of the Dojo Coding community. I’ve contributed to the project in the past regarding the api repository.

### How I plan on tackling this issue
I would approach this issue in the following way, since I’ve read the codebase:
- Since the mapping is being done with a JSON, I would go to `public/starknetid/team.json` and edit the file to remove Head of Art.
- Also, I would go to `public/starknetid/team/` and remove the Head of art.webp file to remove all references to Head of art.
- I would test my implementation by running the frontend and making sure the card is no longer visible.
- I would ask the maintainers if any questions come up while working on this issue

**Comment by bitfalt** [comment] 2024-09-26 07:26
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hii! My name is Daniel, I’m a Computer Science student and web3 developer. I’ve done some contributions, finished a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings and I have participated in multiple Hackathons. I’m also a member of the Dojo Coding community. I’ve contributed to the project in the past regarding the api repository.

### How I plan on tackling this issue
I would approach this issue in the following way, since I’ve read the codebase:
- Since the mapping is being done with a JSON, I would go to `public/starknetid/team.json` and edit the file to remove Head of Art.
- Also, I would go to `public/starknetid/team/` and remove the Head of art.webp file to remove all references to Head of art.
- I would test my implementation by running the frontend and making sure the card is no longer visible.
- I would ask the maintainers if any questions come up while working on this issue

**Comment by MatiasAchucarro** [comment] 2024-09-26 07:27
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, and C# with .NET Entity Framework, among others. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration. I have already made a contribution to Starknet Quest, and I am eager to take on more opportunities

### How I plan on tackling this issue
To delete the "Head of Art" card, I locate the .tsx or .js file where it's rendered. I search for the JSX or TSX block generating the card, remove it from the return or render, and then compile the project. I check in the browser to ensure the card is no longer displayed and that there are no errors in the console.

**Comment by PabloVillaplana** [comment] 2024-09-26 07:33
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack developer with 6 years of experience in the industry, I am super excited to be able to contribute to Web 3 projects, this to continue paving my way as an Open Source Contributor. I am from Dojo Coding Community

### How I plan on tackling this issue
I would like to contribute Starknet Quest again with this issue, I think I can remove the contributor easily and it wouldn't take me more than 1h to do it

**Comment by martinvibes** [comment] 2024-09-26 07:46
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo


### How I plan on tackling this issue
this issue is easy tackle please kindly :)

**Comment by mariocodecr** [comment] 2024-09-26 07:47
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.

### How I plan on tackling this issue
Since I’ve familiarized myself with the codebase, I would first locate the section of the code where the "Head of art" card is being rendered. After identifying the relevant component or template, I would remove the card by editing the corresponding code or data source. I would also check if any related assets, such as images or styles, are linked to the card and remove them to keep the codebase clean.

To ensure the changes are correctly applied, I would run tests and verify that the "Head of art" card is no longer visible on the partnership page, confirming the layout remains unaffected. If any doubts arise during the process, I would reach out to the maintainers for clarification.

**Comment by Luluameh** [comment] 2024-09-26 07:49
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have experience working with JavaScript and TypeScript, particularly in building and maintaining web applications using frameworks like React and libraries such as Chakra UI and Mantine. My work involves creating dynamic components, managing state, and ensuring efficient DOM manipulation. I’ve handled similar tasks of modifying UI elements, updating or removing components as needed, and ensuring the application functions correctly post-modification.

My background in web development, including projects where I had to implement, modify, and troubleshoot various components on different pages, makes me well-equipped to handle tasks like removing elements such as the "Head of art" card from the partnership page. I also have experience working with design systems, so I can ensure the UI remains cohesive after the card is removed.

### How I plan on tackling this issue
To remove the "Head of art" card from the partnership page, I would approach the problem as follows:

Understand the codebase: I would first locate the partnership page within the project structure and inspect how the "Head of art" card is currently rendered. If the card is dynamically populated, I will track the data source or component responsible for it.

Remove the card: Depending on the code implementation, I would either remove the JSX code for the card directly or adjust the logic that generates it. If it is conditionally rendered, I’ll ensure that the condition for showing the card no longer evaluates to true.

Ensure visual consistency: After removing the card, I would check how the rest of the layout is affected. Any potential spacing or alignment issues caused by removing the card will be corrected to maintain a clean design.

Test the page: I would thoroughly test the page to ensure no other components are unintentionally affected by this change. This includes cross-browser testing and checking the mobile responsiveness if applicable.

**Comment by evgongora** [comment] 2024-09-26 08:00
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi I'm Erick part of Dojo Coding, and I'll be working on issue #841.

With my experience in web development, particularly using React, I’m well-suited to handle this task. I've worked on component-based UI development, including making design adjustments and maintaining responsive layouts. 

### How I plan on tackling this issue
I estimate this task will take about less than a day to complete.

Here’s my approach to resolving this issue:

Review the current codebase to locate the section where the "Head of Art" card is being rendered.
Remove the relevant component responsible for rendering the card.
Test the page to ensure the structure, design, and responsiveness remain unaffected by the removal.
Conduct a self-review to confirm all aspects of the change align with the desired outcome.
If everything looks good, I'll submit a PR for final review and integration into the main repository.

**Comment by Solomonsolomonsolomon** [comment] 2024-09-26 08:45
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Fullstack developer 

### How I plan on tackling this issue
This is a simple issue,I will remove the head of art card from the component

**Comment by Benjtalkshow** [comment] 2024-09-26 08:58
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
With my experience in frontend development using Next.js, React, and TypeScript, I’ve contributed to multiple projects focusing on UI/UX improvements. This task requires a straightforward removal of a specific card from the partnership page, and based on my previous work with dynamic component structures, I’m confident that I can carry this out efficiently without affecting the overall layout of the page.

**Comment by Agbeleshe** [comment] 2024-09-26 09:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a full stack developer with 3 years experience in HTML, CSS JavaScript, node.js React, Typescript and other libraries and frameworks.

### How I plan on tackling this issue
I would love this to be my first contribution please.
I will locate the 'Head of Art' details  in the card array or object and highlight the entire  'Head of Art' card details and... smash that delete button!!!!

**Comment by SoarinSkySagar** [comment] 2024-09-26 09:18
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
GM, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. You can see my projects and contributions to some major repos on my GitHub profile. The tech stack I use mainly includes Solidity, Rust, JavaScript and Typescript. I am also contributing to the Starknet and Rust ecosystems and building on Cairo and Rust languages. I am interested in contributing to projects like this to learn more about these technologies and help make these projects better. Please assign me as I would be really glad to be a contributor in this project! :)

### How I plan on tackling this issue
Hi @Marchand-Nicolas, I would
- locate the file with the Head of Art card
- select the component and delete it
- Ensure no errors are being created due to this and make the UI consistent

### Tasks:
- [ ] Delete the card

## ETA: 1 Hour

**Comment by EnochScript** [comment] 2024-09-26 09:22
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a frontend developer with expertise in JavaScript and react. This is my first time contributing to open source and I will like the opportunity to contribute to this project. I have good technical knowledge; I have the ability to work under pressure and adapt quickly and these will help me to contribute effectively to solving diverse challenges.

### How I plan on tackling this issue
a. I will examine the HTML structure to locate the structure of the head of art card
b. Using JavaScript, I will select the card by its unique class or by its content and remove the card

**Comment by melnikga** [comment] 2024-09-26 09:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Can I take this? I’ve participated in almost every ODHack. I have extensive experience in frontend development. I can handle this task.



### How I plan on tackling this issue

My profile on OD: https://app.onlydust.com/u/melnikga

**Comment by Marchand-Nicolas** [comment] 2024-09-29 09:57
Done here: https://github.com/lfglabs-dev/starknet.quest/pull/847

**Closed as completed by Marchand-Nicolas** 2024-09-29 09:57 UTC
Labels: Good first issue
