### ISSUE TITLE
Quiz on Ekubo quest

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#594] opened 2024-04-16 14:43 UTC
In the Ekubo quest, the quiz redirects to the Ekubo platform, making it impossible to complete the quest.

https://www.loom.com/share/7b6fd1687f1a4689adb5120d935bf15b

**Comment by zintarh** [comment] 2024-04-16 17:00
Hi @ayushtom please can this be assign to me

**Comment by Dprof-in-tech** [comment] 2024-04-17 02:37
hi @ayushtom 
please assign this to me

**Comment by fricoben** [comment] 2024-04-17 14:00
Not a bug, but the CTA should have a different naming. I changed it to `Learn more about Ekubo`

**Closed as completed by fricoben** 2024-04-17 14:00 UTC
Labels: 🚨 Important bug
