### ISSUE TITLE
The profile picture doesn't appear on the dashboard

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#973] opened 2024-12-03 14:26 UTC
## Description 📹

**The profile picture doesn't appear on the dashboard, check if there is a loading issue.**

<img width="1440" alt="Screenshot 2024-12-03 at 14 39 17" src="https://github.com/user-attachments/assets/0cac8f3a-504d-4ebc-b545-b9459ead7554">

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by OWK50GA** [comment] 2024-12-03 14:30
Hey @Kevils
I can work on this

**Comment by wheval** [comment] 2024-12-03 14:32
Hello @Kevils . I can fix this ASAP

**Comment by michojekunle** [comment] 2024-12-05 07:29
Hi, I’d like to work on the issue to resolve the profile picture not appearing on the dashboard. 

My approach:

- Analyze the Issue: Debug the profile picture loading process to identify the cause (e.g., broken link, API error).
- Implement Fix: Address the issue by correcting the loading mechanism or updating the link/source.
- Test Locally: Ensure the profile picture loads correctly and consistently across all scenarios.
- Submit PR: Follow the repo’s workflow and reference the issue in the PR.

I’ll complete this task within the 3-day timeframe, ensuring a robust and reliable fix.

Looking forward to your approval to proceed!

**Comment by aurlic** [comment] 2024-12-05 21:55
I would be glad to be able to work on this issue and help contribute to this project !

**Comment by dare117** [comment] 2024-12-05 22:06
I’d love to work on this task.

**Comment by PrathamJha1** [comment] 2024-12-07 18:05
I'd like to handle this task.

**Comment by ryzen-xp** [comment] 2024-12-08 09:21
Hi,
 I am proficient Blockchain developer  expert in web development.
I have  contributed many stark net project and more  . 
 please /assign  this issue .
Thank You

**Comment by Emmykeyz101** [comment] 2024-12-09 20:38
Can I try solving this issue?

**Comment by Shalomnze** [comment] 2024-12-10 01:33
I’d like to resolve this.

**Comment by 3th-Enjay** [comment] 2024-12-11 07:58
May I be assigned to this?

**Comment by michojekunle** [comment] 2024-12-14 08:16
Hi @Kevils Thank you for assigning me this issue 

Please is it possible to get a starknet id using testnet

**Closed as completed** 2024-12-15 10:54 UTC
Labels: open for contribution, Good first issue
