### ISSUE TITLE
Haiko favicon doesn't work 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#849] opened 2024-10-03 20:47 UTC
## Description 

The Haiko favicon isn't rendering well cause the URL is `src="/haiko_solvers/favicon.ico"` but it should be src="/haiko/favicon.ico"
https://starknet.quest/discover/defi

<img width="409" alt="Capture d’écran 2024-10-03 à 21 45 14" src="https://github.com/user-attachments/assets/b18d2425-1acb-4b1f-a009-1795c6564aa9">

Please fix and make it appear well !

**Comment by Oshioke-Salaki** [comment] 2024-10-03 20:53
Please can I do this?

**Comment by GideonBature** [comment] 2024-10-03 20:58
Could you assign this to me?

Thank you.

**Comment by danielcdz** [comment] 2024-10-03 21:01
Hello @fricoben im new to this project I have good expertise and made a lot of contributions to other projects in OnlyDust, I'll be happy to help with this one!

**Comment by martinvibes** [comment] 2024-10-03 21:19
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
hello i would love to work on this issue please kindly assign 

I have good expertise and experience using react, javascript, typescript, css, sass, tailwind css e.t.c  and I'll be happy to help with this one! please kindly assign :)

**Comment by NueloSE** [comment] 2024-10-03 21:33
@fricoben kindly assign me this task i would like to make it my first contribution to this project

**Comment by ShantelPeters** [comment] 2024-10-03 21:36
Hi @fricoben please can I be assigned to this issue ?

**Comment by Kaminar-i** [comment] 2024-10-03 21:39
hello @fricoben i would love to work on this issue please kindly assign :)

**Comment by deeseeker** [comment] 2024-10-03 21:47
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I would like to work on this issue @fricoben. please give me the chance to get more familiar with the project

**Comment by guha-rahul** [comment] 2024-10-03 22:10
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have experience as a web dev

### How I plan on tackling this issue
I will fix this issue by updating the favicon URL in the image file. The current URL is incorrect and points to a non-existent directory. Here's the plan:

Locate the image file where the favicon is defined
Change the favicon URL from /haiko_solvers/favicon.ico to /haiko/favicon.ico.
Verify that the favicon file exists in the /haiko/ directory.
Test the change locally to ensure the favicon appears correctly.

**Comment by Benjtalkshow** [comment] 2024-10-03 22:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
My name is Benjamin, a Fullstack Developer with expertise in JavaScript, Next.js, and TypeScript, and a passion for frontend technologies. 

### How I plan on tackling this issue
I would be glad to quickly work on this task, as I have mastered the project files and structure, and know how to optimize and fix frontend related issues. Thanks.

**Comment by MatiasAchucarro** [comment] 2024-10-04 00:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, and C# with .NET Entity Framework, among others. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration. I have already made a contribution to Starknet Quest, and I am eager to take on more opportunities

### How I plan on tackling this issue
To fix the favicon issue, I would find the reference to the file in the HTML and correct the path from src="/haiko_solvers/favicon.ico" to src="/haiko/favicon.ico". I would then test the change locally to ensure the favicon displays correctly, and finally deploy it to production to verify the issue is resolved.

**Comment by fricoben** [comment] 2024-10-04 07:55
Let's go @danielcdz I assigned to you. 

For the others, more issues will come soon to front-end and back-end

**Comment by danielcdz** [comment] 2024-10-04 14:34
Thank you @fricoben !

**Closed as completed** 2024-10-07 09:09 UTC
Labels: open for contribution, Good first issue
