### ISSUE TITLE
Fix boost token

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#882] opened 2024-10-14 17:38 UTC
close: [#284 ](https://github.com/lfglabs-dev/api.starknet.quest/issues/284)

In the admin dashboard, when editing the boost of a quest, we cannot change the token: it always shows "USDC".
Also we would like not to send the token name to the API, but rather the token contract.

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/f5ec812f-6ac4-4645-b113-65bd87e73a34">

**Proposed to do**
- In `components/admin/formSteps/RewardDetailsForm.tsx` near line 145, you could, rather than setting the value to `eachItem`, which is the token name, replace it by something like `TOKEN_ADDRESS_MAP[network][eachItem]` which returns the token address. You can check using the browser dev tools, in the "network" tab, that the request contains the token address and not its name.
- Also fix the issue where it always shows "USDC" even after selecting another token

**Comment by NueloSE** [comment] 2024-10-14 17:42
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am experienced in using JavaScript and typescript for type safety. With this experience of mine i can handle this bug fix

### How I plan on tackling this issue
- i will use a mapping between token names and addresses (TOKEN_ADDRESS_MAP) for consistency.
- i would ensure to keep sensitive information (token addresses) out of the frontend display.
- and I would finaly ensure the backend receives the correct data format (token addresses).

**Comment by sajalbnl** [comment] 2024-10-14 17:43
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by Iwueseiter** [comment] 2024-10-14 17:43
Hi @Marchand-Nicolas can I be assigned to this task?

**Comment by martinvibes** [comment] 2024-10-14 17:44
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
hello @Marchand-Nicolas i would love to workl on this issue? :)
Thanks

### How I plan on tackling this issue
I would simply understand what the issue is and tackle it

**Comment by 0xdevcollins** [comment] 2024-10-14 17:46
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
can i be assigned this task? I will deliver in less than 24 hrs

**Comment by Bosun-Josh121** [comment] 2024-10-14 17:47
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
software engineering background looking to make first contribution on this project(https://app.onlydust.com/u/Josh-121)

### How I plan on tackling this issue
Update the token selection logic to use the contract address by utilizing a TOKEN_ADDRESS_MAP.
Fix the display issue by ensuring the correct token is shown based on user input.
Confirm through browser dev tools that the correct data is being sent to the API.
This approach ensures both the UI and API interaction behave as expected.

work on any feedback and can deliver within 1-2 days

**Comment by Benjtalkshow** [comment] 2024-10-14 17:48
@Marchand-Nicolas 
Can you assign this task to me? I am wiling to tackle this issue immediately. Thanks

**Comment by ooochoche** [comment] 2024-10-14 17:50
@Marchand-Nicolas Can I be assigned this issue? I have gone through the description and I can resolve the issue.

**Comment by PoulavBhowmick03** [comment] 2024-10-14 17:50
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue

I'll update `RewardDetailsForm.tsx` by modifying the `Dropdown` to use token contract addresses from `TOKEN_ADDRESS_MAP` as the `value` instead of token names. I'll also update the `handleBoostTokenChange` function to set the selected token's address in `boostInput.token` and ensure the form state correctly reflects the chosen token to prevent it from defaulting to "USDC". This will ensure the API receives the token contract address instead of the token name.

1. **Understand the Current Implementation:**
   - Review the `RewardDetailsForm.tsx` component
   - Identify where the token name ("USDC") is being hardcoded or defaulted in the form state or props.

2. **Implement Token Address Mapping:**
   - Introduce a `TOKEN_ADDRESS_MAP` that maps each network to its corresponding token addresses. This can be defined in a configuration file or within the component, depending on the project's structure.
   - Modify the value assignment in `RewardDetailsForm.tsx` so that instead of setting the token value to `eachItem` (the token name), it uses `TOKEN_ADDRESS_MAP[network][eachItem]` to retrieve and set the token address.

3. **Update the Token Selection Logic:**
   - Ensure that the token selection dropdown or input allows selecting different tokens and correctly updates the form state with the selected token address.
   - Remove any hardcoded default values (like "USDC") and set the initial state based on available tokens and their addresses.

4. **Modify API Request Payload:**
   - Update the API request logic to send the token contract address instead of the token name. This may involve changing the payload structure or the specific fields being sent.
   - Ensure that any API calls related to updating the boost now include the `tokenAddress` instead of `tokenName`.
   
ETA - 2 days

**Comment by thiagoulloa** [comment] 2024-10-14 17:51
Can I work on this? @Marchand-Nicolas

**Comment by joeperpetua** [comment] 2024-10-14 17:56
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Fullstack Js/Ts experience

**Comment by ShantelPeters** [comment] 2024-10-14 17:58
Hi @Marchand-Nicolas can i please be assigned to this issue?

**Comment by nemealfaro** [comment] 2024-10-14 18:03
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
My name is Némesis Alfaro, I'm a System Engineer focused on frontend, database and IT business administrator.
I love  to learn and practice about different tecnologies.
I'm hard-working, constant and curious person
This would be my first contribution on the platform, in order to gain more knowledge and improve in the area.



### How I plan on tackling this issue
First, i would like carefully read the request and be in  contact with you for more infomation also investigate similar cases about that, to make execution plan and solve that problem as soon is possible, i estimate no more of three days

**Comment by zleypner** [comment] 2024-10-14 18:06
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I’m a Software Developer with +3 years of experience, and I would love 
 continue making contribution to this project 
I'm also a member of the Dojo Coding community CR.

### How I plan on tackling this issue
I would update components/admin/formSteps/RewardDetailsForm.tsx to use TOKEN_ADDRESS_MAP[network][eachItem] for the token address instead of the name, and ensure the selected token displays correctly instead of always showing "USDC."

**Comment by KevinLatino** [comment] 2024-10-14 23:40
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a web development enthusiast with a passion for both frontend and backend technologies. While this would be my first contribution to an open-source project, I have experience working with React, TypeScript, and API integrations. I enjoy tackling complex problems and learning from them, which makes me confident that my background in web development will help me effectively contribute to your project. I'm particularly skilled in troubleshooting and enhancing functionality in UI forms, as well as improving API request handling.

### How I plan on tackling this issue
First, I would investigate why the token dropdown always displays "USDC" by checking how the state for the token is being initialized and updated in the RewardDetailsForm.tsx file. I’d ensure that the token dropdown correctly reflects the selected token from the TOKEN_ADDRESS_MAP[network] data structure, which maps the token names to their respective contract addresses. To fix the API request, I would modify the form logic so that instead of sending the token name (eachItem), it sends the token contract address using TOKEN_ADDRESS_MAP[network][eachItem]. Lastly, I would verify in the browser's dev tools that the request now contains the token contract address.

**Comment by fishseabowl** [comment] 2024-10-15 00:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a top contributor on OnlyDust, specializing in Starknet.

### How I plan on tackling this issue
Based on the comments, I believe it should be completed in about a couple of hours.

**Comment by Benjtalkshow** [comment] 2024-10-15 07:02
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack Developer with extensive experience in blockchain and web development, specializing in Next.js, TypeScript, Node.js, and Rust. With over 21 contributions across various projects within the OnlyDust ecosystem, I have honed my skills in delivering high-quality solutions, tackling both frontend and backend challenges, and working with complex integrations like token management.

### How I plan on tackling this issue
To address the issue of the token always displaying as "USDC" and sending the token name instead of its contract address to the API, I will proceed as follows:

1. I will begin by reviewing the `RewardDetailsForm.tsx` component, particularly the area around line 145 where the token name is being set. I’ll investigate the state management and token selection logic to pinpoint why "USDC" is persistently shown regardless of the selected token.

2. I’ll update the logic to ensure that instead of setting the token name, it sets the contract address. This can be done by replacing eachItem with a reference to a `TOKEN_ADDRESS_MAP[network][eachItem]`, which will provide the correct token address for the selected network.

3. I will use the browser’s developer tools, specifically the "Network" tab, to confirm that the API requests now contain the token contract address rather than the token name. This will ensure that the correct data is being sent and that the API can properly handle token details.

4. I’ll investigate why the token selection always defaults to "USDC," ensuring that when a new token is selected, the form correctly reflects the chosen token and updates accordingly. I will update any necessary state handling to dynamically display the selected token's address. 

Lastly, After making these adjustments, I will thoroughly test the form, both with different tokens and networks, ensuring that it behaves as expected. I'll also validate that the correct data is sent to the API under various conditions.

**Comment by ooochoche** [comment] 2024-10-16 08:46
@Marchand-Nicolas, please can you help me with the admin passcode? I want to test the requested changes to the dashboard to ensure it's not showing USDC alone. I am trying to get your Telegram account. Here is mine, @oxbenie.

**Closed as completed** 2024-10-17 12:49 UTC
Labels: 🚨 Important bug, open for contribution, Good first issue
