### ISSUE TITLE
Connecting with Argent web wallet on mainnet gives an application side error

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#559] opened 2024-03-21 18:02 UTC
<img width="1111" alt="Capture d’écran 2024-03-21 à 15 01 41" src="https://github.com/starknet-id/starknet.quest/assets/78437165/c6e1ffeb-a7c8-4f96-9ade-dd7cd16999d7">
<img width="465" alt="Capture d’écran 2024-03-21 à 15 02 02" src="https://github.com/starknet-id/starknet.quest/assets/78437165/50f6dec0-4685-472f-a31b-f0946c52b566">

Tried to connect on https://starknet.quest/quest/107 so maybe a `.?` missing on the quest page, it should take 10-20 minutes to find.

**Comment by raizo07** [comment] 2024-03-21 18:18
Hello, can you assign this to me?

**Comment by Ayoazeez26** [comment] 2024-03-21 18:20
Hi @fricoben , can I pick this up?

**Comment by JeffreyJoel** [comment] 2024-03-21 19:51
Hi @fricoben, please can I be assigned to this?

**Comment by ayushtom** [comment] 2024-03-22 09:19
@raizo07 assigned to you!
@JeffreyJoel @Ayoazeez26 i am assigning on a first come first serve basis so i would invite you to pick from any other available issues.

**Comment by raizo07** [comment] 2024-03-22 11:31
@ayushtom @fricoben I was able to connect to Argent web wallet successfully on both mainnet and testnet without getting the error described above, so I don't know if more detailed explanation can be provided for the error described in order for me to look into it. Thank you.

**Comment by ayushtom** [comment] 2024-03-23 17:08
@raizo07 can you check with a ongoing quest ?

**Comment by raizo07** [comment] 2024-03-25 09:25
Yes, I'm on it.

**Comment by ayushtom** [comment] 2024-03-28 12:13
@raizo07 what's the status on this? we will have to reassign to someone else if we don't resolve this today

**Comment by raizo07** [comment] 2024-03-28 12:17
Yes, I am working on it. Although I asked a question, the API calls are
failing and I don't know why. I'll be sending a screenshot of it.

**Comment by raizo07** [comment] 2024-03-28 15:43
Hello @ayushtom, I've checked again with an ongoing quest and it gives the below attached error when connected with Argent wallet although Braavos works fine. I'm on it and should make a PR available soon.
![image](https://github.com/starknet-id/starknet.quest/assets/81079370/05133161-9745-442a-be88-ee589ff476bb)

**Comment by ayushtom** [comment] 2024-03-29 12:49
Are you able to recreate the screenshot given in the description? @raizo07

**Comment by fricoben** [comment] 2024-03-29 16:53
> Hello @ayushtom, I've checked again with an ongoing quest and it gives the below attached error when connected with Argent wallet although Braavos works fine. I'm on it and should make a PR available soon. ![image](https://private-user-images.githubusercontent.com/81079370/317789978-05133161-9745-442a-be88-ee589ff476bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MzE0NjUsIm5iZiI6MTcxMTczMTE2NSwicGF0aCI6Ii84MTA3OTM3MC8zMTc3ODk5NzgtMDUxMzMxNjEtOTc0NS00NDJhLWJlODgtZWU1ODlmZjQ3NmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE2NTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MmUwYTU3Yzg2YWQ2ZWExMGM0ZTMzYTM1ODYzYmEyMGFlZWJhZGQ0ODRkNDQ1M2VhOTNkYThkOWQxZjVkNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DGZTdlxSE1jfZ1gLTlraTK7HVhaaKKPDIrEiA74lDqc)

You need to connect with web wallet

**Comment by raizo07** [comment] 2024-03-29 17:20
@fricoben Yes I connected using a web wallet.

**Comment by ayushtom** [comment] 2024-03-30 10:36
@raizo07 any update on this? i would be reassigning this issue today if we don't see a fix PR. All the best if you're working on it already

**Comment by raizo07** [comment] 2024-03-30 10:40
Yes, I am working on it.

**Comment by ayushtom** [comment] 2024-03-31 08:23
I dont see a PR yet so i would be assigning to anyone who wants to work on this

**Comment by Ayoazeez26** [comment] 2024-03-31 08:41
@ayushtom I am unable to reproduce the error in the screenshot given in the description. I headed over to https://starknet.quest/quest/107 and connected my Argent web wallet and I did not get the said error. The screenshot below contains the errors that came up and they didn't break the application.


![error shown when connected to argent web wallet on mainnet](https://github.com/starknet-id/starknet.quest/assets/44169294/b24c0a4d-9021-4e22-b14e-50a464f9c394)

**Comment by saimeunt** [comment] 2024-04-03 20:52
@ayushtom Hey I'd like to try fixing this one please!

**Comment by JeffreyJoel** [comment] 2024-04-03 21:06
Hi @ayushtom, can I be assigned to this?

**Comment by ayushtom** [comment] 2024-04-08 08:58
@saimeunt assigning to you!

**Comment by ayushtom** [comment] 2024-04-08 08:59
unassigned @raizo07 since the issue has taken a long time to close till now and not much meaningful process could be made

**Comment by saimeunt** [comment] 2024-04-13 19:33
@ayushtom I investigated this bug, this is what I find out:

The culprit of the bug is caused by a proxy creation in trpc/client : https://github.com/trpc/trpc/blob/next/packages/client/src/createTRPCClient.ts#L142
Somehow this gets called with `toJSON` as `key` and an empty array as `path` and failing because `procedureType` is undefined.

The proxy is created in the web wallet connector here: https://github.com/argentlabs/starknetkit/blob/v1.1.4/src/connectors/webwallet/helpers/trpc.ts#L103

The web wallet connection error only happens if using a `useContractWrite` in the reward component here: https://github.com/starknet-id/starknet.quest/blob/testnet/components/quests/reward.tsx#L44

I'm not sure how to fix this as I was unable to understand the chain of events that leads the proxy creation process to get called on an invalid method (namely `toJSON`).

Another thing I noticed is that the project is still using an old version of starknetkit (v1.1.4) whereas the latest version is now v2.2.6
The version we're using at the moment hardcodes Goerli as testnet in the webwallet interface so it is mandatory to upgrade to v2 of starknetkit to use Sepolia instead.

Upgrading to v2 may (or may not) have the beneficial side effect of getting rid of this odd bug so what I'm suggesting is that we should close this issue and raise a new one to upgrade starknetkit to v2.
I'd like to get assigned to upgrading starknetkit to v2 as well as starknetjs v6 as it is a peerDependency.

**Closed as completed** 2024-07-30 17:02 UTC
Labels: open for contribution
