### ISSUE TITLE
Fixed the glitch showed on the video in the notification component

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#820] opened 2024-08-19 08:23 UTC
## Video Description 

https://www.loom.com/share/9a9eb7c0561e489cadef16b3a23943a1

Fixed the glitch showed on the video in the notification component

**Comment by EjembiEmmanuel** [comment] 2024-08-19 08:27
@fricoben can I work on this?

**Comment by ooochoche** [comment] 2024-08-19 08:29
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
@fricoben I can work on this, if no one is assigned to it

### How I plan on tackling this issue
After carefully watching the video I would approach this issues by:

- Understanding and analyzing the glitch triggers.
- Try to reproduce the glitch in the development environment.
- Look into the code for the notification component and dependencies.
- Isolate the Issue causing the glitch.
- Identify the issue and implement fix.
- Test and review.

**Comment by GoSTEAN** [comment] 2024-08-19 08:42
@fricoben Can I work on this?

**Comment by ShantelPeters** [comment] 2024-08-21 17:26
@fricoben can I work on this issue ? I will raise a PR immediately after I am assigned..

**Comment by petersdt** [comment] 2024-08-21 19:23
@fricoben can i be assigned this task

**Comment by od-hunter** [comment] 2024-08-21 19:26
Hi @fricoben , can I work on this?

**Comment by aokiji233** [comment] 2024-08-21 20:57
Hey ! I'm an passionate and experienced software engineer working currently in startup (AI field), but I'm growing a strong interest on web3 and espacially in starknet. It will be my first contribution, I would love to be involved in this very exciting project  ! :)

I will explore the notification component and the component responsible to display the wallet address. I will check for the interaction in those and try to understand how they could possibly be linked. Once I understand the problem I will think on the best and most simple way to patch it.

**Comment by lindsaymoralesb** [comment] 2024-08-22 07:48
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi! My name is Lindsay, and I'm a Software Engineer based in Costa Rica. I'm part of Dojo Coding and thanks to that I've already successfully contributed to 4 ODHacks in various projects, feel free to check my profile and contributions.
I've been working over the past 4.5 years as a full stack developer, specializing myself in frontend development. I've successfully integrated APis, developed new features, optmize projects, improving responsiveness, etc with the most known/used FE frameworks such as React, Next, Vue, and Angular. All this experience plus some courses I've taken had helped me master both javascript and typescript languages.

### How I plan on tackling this issue
First I'll start by setting up and get the project running.
After that I'll try to reproduce the issue locally as shown on the video.
Then, I'll start debugging the platform to encounter where the issue is happening.

**Comment by Dprof-in-tech** [comment] 2024-08-22 08:01
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
As an experienced Full Stack Blockchain Developer, I'm excited to contribute my expertise to Edition 7 of the OnlyDust hackathons. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Solidity, and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 28 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.
My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we embark on Edition 7, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.
With a passion for creating cutting-edge solutions, I'm excited to collaborate with the OnlyDust community and contribute to the advancement of the blockchain ecosystem.


### How I plan on tackling this issue
I looked through the video and i figure it could be a state management problem but i would need to look through the issue to solve it.

I am confident in solving this issue and would be sure to give feedback reports as require

**Comment by Ugo-X** [comment] 2024-08-22 08:14
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

**Comment by josephchimebuka** [comment] 2024-08-22 08:38
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged

Hello @FricoBen I am Joseph Chimebuka I'm a full-stack software developer with 4+ years of experience in crafting innovative products. I've built a range of projects, including https://mattedsgn.vercel.app/  and  https://metacrypt.vercel.app/  showcasing my expertise in React, Next.js, and blockchain technologies. I'm also an active contributor onlydust. here's my account https://app.onlydust.com/u/josephchimebuka.

### How I plan on tackling this issue
1. I'll check the code where notifications are triggered and look for any conditions or events that might be causing them to fire unexpectedly.
2. I'll identify and remove or comment out any unnecessary notification logic, ensuring they only trigger during specific, intended events.

3. I'll review the state management to ensure the notification state is updated correctly, preventing unintended notifications.

4.I'll test the page thoroughly to confirm that notifications appear only when expected.

**Comment by ahmadou-ai** [comment] 2024-08-22 08:39
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hey ! I'm an passionate and experienced software engineer working currently in startup (AI field), but I'm growing a strong interest on web3 and espacially in starknet. It will be my first contribution, I would love to be involved in this very exciting project ! :)



### How I plan on tackling this issue
I think this is due to a side effect, Iwill explore the notification component and the component responsible to display the wallet address. I will check for the interaction in those and try to understand how they could possibly be linked. Once I understand the problem I will think on the best and most simple way to patch it.

**Comment by Marchand-Nicolas** [comment] 2024-08-24 20:22
https://github.com/starknet-id/starknet.quest/pull/829

**Closed as completed by Marchand-Nicolas** 2024-08-24 20:22 UTC
Labels: open for contribution
